// This file is autogenerated by hexya-generate
// DO NOT MODIFY THIS FILE - ANY CHANGES WILL BE OVERWRITTEN

package m

import (
	"github.com/beevik/etree"
	"github.com/hexya-addons/web/domains"
	"github.com/hexya-addons/web/webtypes"
	"github.com/hexya-erp/hexya/src/actions"
	"github.com/hexya-erp/hexya/src/models"
	"github.com/hexya-erp/hexya/src/models/operator"
	"github.com/hexya-erp/hexya/src/models/types"
	"github.com/hexya-erp/hexya/src/models/types/dates"
	"github.com/hexya-erp/pool/q"
)

// QueueJobSet is an autogenerated type to handle QueueJob objects.
type QueueJobSet interface {
	models.RecordSet
	// QueueJobSetHexyaFunc is a dummy function to uniquely match interfaces.
	QueueJobSetHexyaFunc()
	// ForceLoad reloads the cache for the given fields and updates the ids of this QueueJobSet.
	//
	// If no fields are given, all DB columns of the QueueJob model are retrieved.
	//
	// It also returns this QueueJobSet.
	ForceLoad(fields ...models.FieldName) QueueJobSet
	// Arguments is a getter for the value of the "Arguments" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	Arguments() string
	// SetArguments is a setter for the value of the "Arguments" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetArguments panics if the RecordSet is empty.
	SetArguments(value string)
	// Channel is a getter for the value of the "Channel" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	Channel() QueueChannelSet
	// SetChannel is a setter for the value of the "Channel" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetChannel panics if the RecordSet is empty.
	SetChannel(value QueueChannelSet)
	// Company is a getter for the value of the "Company" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	Company() CompanySet
	// SetCompany is a setter for the value of the "Company" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetCompany panics if the RecordSet is empty.
	SetCompany(value CompanySet)
	// CreateDate is a getter for the value of the "CreateDate" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	CreateDate() dates.DateTime
	// SetCreateDate is a setter for the value of the "CreateDate" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetCreateDate panics if the RecordSet is empty.
	SetCreateDate(value dates.DateTime)
	// CreateUID is a getter for the value of the "CreateUID" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	CreateUID() int64
	// SetCreateUID is a setter for the value of the "CreateUID" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetCreateUID panics if the RecordSet is empty.
	SetCreateUID(value int64)
	// DateDone is a getter for the value of the "DateDone" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	DateDone() dates.DateTime
	// SetDateDone is a setter for the value of the "DateDone" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetDateDone panics if the RecordSet is empty.
	SetDateDone(value dates.DateTime)
	// DateEnqueued is a getter for the value of the "DateEnqueued" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	DateEnqueued() dates.DateTime
	// SetDateEnqueued is a setter for the value of the "DateEnqueued" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetDateEnqueued panics if the RecordSet is empty.
	SetDateEnqueued(value dates.DateTime)
	// DateStarted is a getter for the value of the "DateStarted" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	DateStarted() dates.DateTime
	// SetDateStarted is a setter for the value of the "DateStarted" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetDateStarted panics if the RecordSet is empty.
	SetDateStarted(value dates.DateTime)
	// DisplayName is a getter for the value of the "DisplayName" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	DisplayName() string
	// SetDisplayName is a setter for the value of the "DisplayName" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetDisplayName panics if the RecordSet is empty.
	SetDisplayName(value string)
	// ETA is a getter for the value of the "ETA" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	ETA() dates.DateTime
	// SetETA is a setter for the value of the "ETA" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetETA panics if the RecordSet is empty.
	SetETA(value dates.DateTime)
	// ExcInfo is a getter for the value of the "ExcInfo" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	ExcInfo() string
	// SetExcInfo is a setter for the value of the "ExcInfo" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetExcInfo panics if the RecordSet is empty.
	SetExcInfo(value string)
	// ExecuteAfterJob is a getter for the value of the "ExecuteAfterJob" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	ExecuteAfterJob() QueueJobSet
	// SetExecuteAfterJob is a setter for the value of the "ExecuteAfterJob" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetExecuteAfterJob panics if the RecordSet is empty.
	SetExecuteAfterJob(value QueueJobSet)
	// ExecuteBeforeJobs is a getter for the value of the "ExecuteBeforeJobs" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	ExecuteBeforeJobs() QueueJobSet
	// SetExecuteBeforeJobs is a setter for the value of the "ExecuteBeforeJobs" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetExecuteBeforeJobs panics if the RecordSet is empty.
	SetExecuteBeforeJobs(value QueueJobSet)
	// HexyaExternalID is a getter for the value of the "HexyaExternalID" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	HexyaExternalID() string
	// SetHexyaExternalID is a setter for the value of the "HexyaExternalID" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetHexyaExternalID panics if the RecordSet is empty.
	SetHexyaExternalID(value string)
	// HexyaVersion is a getter for the value of the "HexyaVersion" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	HexyaVersion() int
	// SetHexyaVersion is a setter for the value of the "HexyaVersion" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetHexyaVersion panics if the RecordSet is empty.
	SetHexyaVersion(value int)
	// ID is a getter for the value of the "ID" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	ID() int64
	// SetID is a setter for the value of the "ID" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetID panics if the RecordSet is empty.
	SetID(value int64)
	// LastUpdate is a getter for the value of the "LastUpdate" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	LastUpdate() dates.DateTime
	// SetLastUpdate is a setter for the value of the "LastUpdate" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetLastUpdate panics if the RecordSet is empty.
	SetLastUpdate(value dates.DateTime)
	// MaxRetries is a getter for the value of the "MaxRetries" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	MaxRetries() int64
	// SetMaxRetries is a setter for the value of the "MaxRetries" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetMaxRetries panics if the RecordSet is empty.
	SetMaxRetries(value int64)
	// Method is a getter for the value of the "Method" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	Method() string
	// SetMethod is a setter for the value of the "Method" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetMethod panics if the RecordSet is empty.
	SetMethod(value string)
	// Model is a getter for the value of the "Model" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	Model() string
	// SetModel is a setter for the value of the "Model" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetModel panics if the RecordSet is empty.
	SetModel(value string)
	// Name is a getter for the value of the "Name" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	Name() string
	// SetName is a setter for the value of the "Name" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetName panics if the RecordSet is empty.
	SetName(value string)
	// Priority is a getter for the value of the "Priority" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	Priority() int64
	// SetPriority is a setter for the value of the "Priority" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetPriority panics if the RecordSet is empty.
	SetPriority(value int64)
	// RecordsIds is a getter for the value of the "RecordsIds" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	RecordsIds() string
	// SetRecordsIds is a setter for the value of the "RecordsIds" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetRecordsIds panics if the RecordSet is empty.
	SetRecordsIds(value string)
	// Result is a getter for the value of the "Result" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	Result() string
	// SetResult is a setter for the value of the "Result" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetResult panics if the RecordSet is empty.
	SetResult(value string)
	// Retry is a getter for the value of the "Retry" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	Retry() int64
	// SetRetry is a setter for the value of the "Retry" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetRetry panics if the RecordSet is empty.
	SetRetry(value int64)
	// State is a getter for the value of the "State" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	State() string
	// SetState is a setter for the value of the "State" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetState panics if the RecordSet is empty.
	SetState(value string)
	// User is a getter for the value of the "User" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	User() UserSet
	// SetUser is a setter for the value of the "User" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetUser panics if the RecordSet is empty.
	SetUser(value UserSet)
	// WriteDate is a getter for the value of the "WriteDate" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	WriteDate() dates.DateTime
	// SetWriteDate is a setter for the value of the "WriteDate" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetWriteDate panics if the RecordSet is empty.
	SetWriteDate(value dates.DateTime)
	// WriteUID is a getter for the value of the "WriteUID" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	WriteUID() int64
	// SetWriteUID is a setter for the value of the "WriteUID" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetWriteUID panics if the RecordSet is empty.
	SetWriteUID(value int64)
	// ActionArchive sets Active=false on a recordset, by calling ToggleActive to take the
	// corresponding actions according to the model
	ActionArchive()
	// ActionUnarchive sets Active=true on a recordset, by calling ToggleActive to take the
	// corresponding actions according to the model
	ActionUnarchive()
	// AddDomainLimitOffset adds the given domain, limit, offset
	// and order to the current RecordSet query.
	AddDomainLimitOffset(domain domains.Domain, limit int, offset int, order string) QueueJobSet
	// AddModifiers adds the modifiers attribute nodes to given xml doc.
	AddModifiers(doc *etree.Document, fieldInfos map[string]*models.FieldInfo)
	// AddNameToRelations returns the given RecordData after getting the name of all 2one relation ids
	AddNamesToRelations(data models.RecordData, fInfos map[string]*models.FieldInfo) models.RecordData
	// AfterJob sets this job to execute only when the given job has succeeded.
	AfterJob(job QueueJobSet) QueueJobSet

	Aggregates(fieldNames ...models.FieldName) []QueueJobGroupAggregateRow
	// Browse returns a new RecordSet with only the records with the given ids.
	// Note that this function is just a shorcut for Search on a list of ids.
	Browse(ids []int64) QueueJobSet
	// BrowseOne returns a new RecordSet with only the record with the given id.
	// Note that this function is just a shorcut for Search on a given id.
	BrowseOne(id int64) QueueJobSet

	CartesianProduct(others ...QueueJobSet) []QueueJobSet
	// CheckAccessRights verifies that the operation given by "operation" is allowed for
	// the current user according to the access rights.
	//
	// operation must be one of "read", "create", "unlink", "write".
	CheckAccessRights(args webtypes.CheckAccessRightsArgs) bool
	// CheckExecutionPermission panics if the current user is not allowed to execute the given method.
	//
	// If dontPanic is false, this function will panic, otherwise it returns true
	// if the user has the execution permission and false otherwise.
	CheckExecutionPermission(method *models.Method, dontPanic ...bool) bool
	// CheckParameters checks if model, method, record ids and arguments are correct
	CheckParameters()
	// CheckRecursion verifies that there is no loop in a hierarchical structure of records,
	// by following the parent relationship using the 'Parent' field until a loop is detected or
	// until a top-level record is found.
	//
	// It returns true if no loop was found, false otherwise`,
	CheckRecursion() bool
	// ComputeDisplayName updates the DisplayName field with the result of NameGet
	ComputeDisplayName() *models.ModelData
	// ComputeLastUpdate returns the last datetime at which the record has been updated.
	ComputeLastUpdate() *models.ModelData

	Copy(overrides QueueJobData) QueueJobSet

	CopyData(overrides QueueJobData) QueueJobData

	Create(data QueueJobData) QueueJobSet

	DefaultGet() QueueJobData
	// Enqueue queues the execution of the given method with the given arguments on this recordset.
	// description will be the name given to the job.
	Enqueue(description string, method models.Methoder, arguments ...interface{}) QueueJobSet
	// Equals returns true if this RecordSet is the same as other
	// i.e. they are of the same model and have the same ids
	Equals(other QueueJobSet) bool
	// ExecuteO2MActions executes the actions on one2many fields given by
	// the list of triplets received from the client
	ExecuteO2MActions(fieldName models.FieldName, info *models.FieldInfo, value interface{}) interface{}
	// Fetch query the database with the current filter and returns a RecordSet
	// with the queries ids.
	//
	// Fetch is lazy and only return ids. Use Load() instead if you want to fetch all fields.
	Fetch() QueueJobSet
	// FieldGet returns the definition of the given field.
	// The string, help, and selection (if present) attributes are translated.
	FieldGet(field models.FieldName) *models.FieldInfo
	// FieldsGet returns the definition of each field.
	// The embedded fields are included.
	// The string, help, and selection (if present) attributes are translated.
	//
	// The result map is indexed by the fields JSON names.
	FieldsGet(args models.FieldsGetArgs) map[string]*models.FieldInfo
	// FieldsViewGet is the base implementation of the 'FieldsViewGet' method which
	// gets the detailed composition of the requested view like fields, mixin,
	// view architecture.
	FieldsViewGet(args webtypes.FieldsViewGetParams) *webtypes.FieldsViewData

	Filtered(test func(QueueJobSet) bool) QueueJobSet
	// FormatRelationFields returns the given data with all relation fields converted to int64 or []int64
	FormatRelationFields(data models.RecordData, fInfos map[string]*models.FieldInfo) models.RecordData
	// GetFormviewAction returns an action to open the document.
	// This method is meant to be overridden in addons that want
	// to give specific view ids for example.`,
	GetFormviewAction() *actions.Action
	// GetFormviewID returns an view id to open the document with.
	// This method is meant to be overridden in addons that want
	// to give specific view ids for example.
	GetFormviewId() string
	// GetRecord returns the Recordset with the given externalID. It panics if the externalID does not exist.
	GetRecord(externalID string) QueueJobSet
	// GetToolbar returns a toolbar populated with the actions linked to this model
	GetToolbar() webtypes.Toolbar
	// GroupBy returns a new RecordSet grouped with the given GROUP BY expressions.
	GroupBy(exprs ...models.FieldName) QueueJobSet
	// Intersect returns a new RecordCollection with only the records that are both
	// in this RecordCollection and in the other RecordSet.
	Intersect(other QueueJobSet) QueueJobSet
	// Limit returns a new RecordSet with only the first 'limit' records.
	Limit(limit int) QueueJobSet
	// Load looks up cache for fields of the RecordCollection and
	// query database for missing values.
	// fields are the fields to retrieve in the expression format,
	// i.e. "User.Profile.Age" or "user_id.profile_id.age".
	// If no fields are given, all DB columns of the RecordCollection's
	// model are retrieved.
	Load(fields ...models.FieldName) QueueJobSet
	// LoadViews returns the data for all the views and filters required in the parameters.
	LoadViews(args webtypes.LoadViewsArgs) *webtypes.LoadViewsData
	// ManageGroupsOnFields adds the invisible attribute to fields nodes if the current
	// user does not belong to one of the groups of the 'groups' attribute
	ManageGroupsOnFields(doc *etree.Document, fieldInfos map[string]*models.FieldInfo)
	// NameGet retrieves the human readable name of this record.`,
	NameGet() string
	// NameSearch searches for records that have a display name matching the given
	// "name" pattern when compared with the given "operator", while also
	// matching the optional search domain ("args").
	//
	// This is used for example to provide suggestions based on a partial
	// value for a relational field. Sometimes be seen as the inverse
	// function of NameGet but it is not guaranteed to be.
	NameSearch(params webtypes.NameSearchParams) []webtypes.RecordIDWithName

	New(data QueueJobData) QueueJobSet
	// NormalizeM2MData converts the list of triplets received from the client into the final list of ids
	// to keep in the Many2Many relationship of this model through the given field.
	NormalizeM2MData(fieldName models.FieldName, info *models.FieldInfo, value interface{}) interface{}
	// Offset returns a new RecordSet with only the records starting at offset
	Offset(offset int) QueueJobSet
	// OnChannel sets the Channel of this job to the channel with the given name
	OnChannel(channel string) QueueJobSet
	// Onchange returns the values that must be modified according to each field's Onchange
	// method in the pseudo-record given as params.Values`,
	Onchange(params models.OnchangeParams) models.OnchangeResult
	// OrderBy returns a new RecordSet ordered by the given ORDER BY expressions.
	// Each expression contains a field name and optionally one of "asc" or "desc", such as:
	//
	// rs.OrderBy("Company", "Name desc")
	OrderBy(exprs ...string) QueueJobSet
	// PostProcessCreateValues updates FK of related records created at the same time.
	//
	// This method is meant to be called with the second returned value of ProcessCreateValues
	// after record creation.
	PostProcessCreateValues(data models.RecordData)
	// PostProcessFilters transforms a map[models.FieldName]models.Conditioner
	// in a map[string][]interface{} which acts as a map of domains.
	PostProcessFilters(in map[models.FieldName]models.Conditioner) map[string][]interface{}
	// ProcessCreateValues updates the given data values for Create method to be
	// compatible with the ORM, in particular for relation fields.
	//
	// It returns a first FieldMap to be used as argument to the Create method, and
	// a second map to be used with a subsequent call to PostProcessCreateValues (for
	// updating FKs pointing to the newly created record).
	ProcessCreateValues(data models.RecordData) (models.RecordData, models.RecordData)
	// ProcessElementAttrs returns a modifiers map according to the domain
	// in attrs of the given element
	ProcessElementAttrs(element *etree.Element, fieldInfos map[string]*models.FieldInfo) map[string]interface{}
	// ProcessFieldElementModifiers modifies the given modifiers map by taking into account:
	// - 'invisible', 'readonly' and 'required' attributes in field tags
	// - 'ReadOnly' and 'Required' parameters of the model's field'
	// It returns the modified map.
	ProcessFieldElementModifiers(element *etree.Element, fieldInfos map[string]*models.FieldInfo, modifiers map[string]interface{}) map[string]interface{}
	// ProcessView makes all the necessary modifications to the view
	// arch and returns the new xml string.`,
	ProcessView(arch *etree.Document, fieldInfos map[string]*models.FieldInfo) string
	// ProcessWriteValues updates the given data values for Write method to be
	// compatible with the ORM, in particular for relation fields
	ProcessWriteValues(data models.RecordData) models.RecordData
	// Read reads the database and returns a slice of FieldMap of the given model.
	Read(fields models.FieldNames) []models.RecordData
	// ReadGroup gets a list of record aggregates according to the given parameters.
	ReadGroup(params webtypes.ReadGroupParams) []models.FieldMap
	// Run this job's method with its arguments. It returns the result of the called method as a string if there is
	// a return value, otherwise a default success string. It panics in cas of error.
	//
	// Note that this method (and its overrides) MUST NOT modify the current job.
	Run() string
	// SQLFromCondition returns the WHERE clause sql and arguments corresponding to
	// the given condition.`,
	SQLFromCondition(c *models.Condition) (string, models.SQLParams)

	Search(condition q.QueueJobCondition) QueueJobSet
	// SearchAll returns a RecordSet with all items of the table, regardless of the
	// current RecordSet query. It is mainly meant to be used on an empty RecordSet.
	SearchAll() QueueJobSet

	SearchByName(name string, op operator.Operator, additionalCond q.QueueJobCondition, limit int) QueueJobSet
	// SearchCount fetch from the database the number of records that match the RecordSet conditions.
	SearchCount() int
	// SearchDomain execute a search on the given domain.
	SearchDomain(domain domains.Domain) CommonMixinSet
	// SearchRead retrieves database records according to the filters defined in params.
	SearchRead(params webtypes.SearchParams) []models.RecordData

	Sorted(less func(QueueJobSet, QueueJobSet) bool) QueueJobSet
	// SortedByField returns a new record set with the same records as rc but sorted by the given field.
	// If reverse is true, the sort is done in reversed order
	SortedByField(namer models.FieldName, reverse bool) QueueJobSet
	// SortedDefault returns a new record set with the same records as rc but sorted according
	// to the default order of this model
	SortedDefault() QueueJobSet
	// Subtract returns a RecordSet with the Records that are in this
	// RecordCollection but not in the given 'other' one.
	// The result is guaranteed to be a set of unique records.
	Subtract(other QueueJobSet) QueueJobSet
	// Sudo returns a new RecordSet with the given userID
	// or the superuser ID if not specified
	Sudo(userID ...int64) QueueJobSet
	// ToggleActive toggles the Active field of this object if it exists.
	ToggleActive()
	// Union returns a new RecordSet that is the union of this RecordSet and the given
	// "other" RecordSet. The result is guaranteed to be a set of unique records.
	Union(other QueueJobSet) QueueJobSet
	// Unlink deletes the given records in the database.
	Unlink() int64
	// WebReadGroup returns the result of a read_group (and optionally search for and read records inside each
	// group), and the total number of groups matching the search domain.
	WebReadGroup(params webtypes.WebReadGroupParams) webtypes.WebReadGroupResult
	// WebReadGroupPrivate performs a read_group and optionally a web_search_read for each group.
	WebReadGroupPrivate(params webtypes.WebReadGroupParams) []models.FieldMap
	// WebSearchRead performs a search_read and a search_count.
	WebSearchRead(params webtypes.SearchParams) webtypes.SearchReadResult
	// WithContext returns a copy of the current RecordSet with
	// its context extended by the given key and value.
	WithContext(key string, value interface{}) QueueJobSet
	// WithEnv returns a copy of the current RecordSet with the given Environment.
	WithEnv(env models.Environment) QueueJobSet
	// WithNewContext returns a copy of the current RecordSet with its context
	// replaced by the given one.
	WithNewContext(context *types.Context) QueueJobSet
	// WithPriority sets this job with the given priority.
	WithPriority(priority int64) QueueJobSet

	Write(data QueueJobData) bool
	// Super returns a RecordSet with a modified callstack so that call to the current
	// method will execute the next method layer.
	//
	// This method is meant to be used inside a method layer function to call its parent,
	// such as:
	//
	//    func (rs h.MyRecordSet) MyMethod() string {
	//        res := rs.Super().MyMethod()
	//        res += " ok!"
	//        return res
	//    }
	//
	// Calls to a different method than the current method will call its next layer only
	// if the current method has been called from a layer of the other method. Otherwise,
	// it will be the same as calling the other method directly.
	Super() QueueJobSet
	// ModelData returns a new QueueJobData object populated with the values
	// of the given FieldMap.
	ModelData(fMap models.FieldMap) QueueJobData
	// Records returns a slice with all the records of this RecordSet, as singleton RecordSets
	Records() []QueueJobSet
	// First returns the values of the first Record of the RecordSet as a pointer to a QueueJobData.
	//
	// If this RecordSet is empty, it returns an empty QueueJobData.
	First() QueueJobData
	// All returns the values of all Records of the RecordCollection as a slice of QueueJobData pointers.
	All() []QueueJobData
}

// QueueJobData is used to hold values of an QueueJob object instance
// when creating or updating a QueueJobSet.
type QueueJobData interface {
	models.RecordData
	// Get returns the value of the given field.
	//
	// The field can be either its name or is JSON name.
	Get(field models.FieldName) interface{}
	// Has returns true if a value is set for the given field.
	//
	// The field can be either its name or is JSON name.
	Has(field models.FieldName) bool
	// Set sets the given field with the given value.
	// If the field already exists, then it is updated with value.
	// Otherwise, a new entry is inserted.
	//
	// It returns the given QueueJobData so that calls can be chained
	Set(field models.FieldName, value interface{}) QueueJobData
	// Unset removes the value of the given field if it exists.
	//
	// It returns the given ModelData so that calls can be chained
	Unset(field models.FieldName) QueueJobData
	// Copy returns a copy of this QueueJobData
	Copy() QueueJobData
	// MergeWith updates this QueueJobData with the given other QueueJobData
	// If a field of the other QueueJobData already exists here, the value is overridden,
	// otherwise, the field is inserted.
	MergeWith(other QueueJobData)
	// Keys returns the QueueJobData keys as a slice of strings
	Keys() (res []string)
	// OrderedKeys returns the keys of this QueueJobData ordered.
	//
	// This has the convenient side effect of having shorter paths come before longer paths,
	// which is particularly useful when creating or updating related records.
	OrderedKeys() []string
	// FieldNames returns the QueueJobData keys as a slice of FieldNames.
	FieldNames() models.FieldNames
	// Arguments returns the value of the Arguments field.
	// If this Arguments is not set in this QueueJobData, then
	// the Go zero value for the type is returned.
	Arguments() string
	// HasArguments returns true if Arguments is set in this QueueJobData
	HasArguments() bool
	// SetArguments sets the Arguments field with the given value.
	// It returns this QueueJobData so that calls can be chained.
	SetArguments(value string) QueueJobData
	// UnsetArguments removes the value of the Arguments field if it exists.
	// It returns this QueueJobData so that calls can be chained.
	UnsetArguments() QueueJobData

	// Channel returns the value of the Channel field.
	// If this Channel is not set in this QueueJobData, then
	// the Go zero value for the type is returned.
	Channel() QueueChannelSet
	// HasChannel returns true if Channel is set in this QueueJobData
	HasChannel() bool
	// SetChannel sets the Channel field with the given value.
	// It returns this QueueJobData so that calls can be chained.
	SetChannel(value QueueChannelSet) QueueJobData
	// UnsetChannel removes the value of the Channel field if it exists.
	// It returns this QueueJobData so that calls can be chained.
	UnsetChannel() QueueJobData

	// CreateChannel stores the related QueueChannelData to be used to create
	// a related record on the fly for Channel.
	//
	// This method can be called multiple times to create multiple records
	CreateChannel(related QueueChannelData) QueueJobData
	// Company returns the value of the Company field.
	// If this Company is not set in this QueueJobData, then
	// the Go zero value for the type is returned.
	Company() CompanySet
	// HasCompany returns true if Company is set in this QueueJobData
	HasCompany() bool
	// SetCompany sets the Company field with the given value.
	// It returns this QueueJobData so that calls can be chained.
	SetCompany(value CompanySet) QueueJobData
	// UnsetCompany removes the value of the Company field if it exists.
	// It returns this QueueJobData so that calls can be chained.
	UnsetCompany() QueueJobData

	// CreateCompany stores the related CompanyData to be used to create
	// a related record on the fly for Company.
	//
	// This method can be called multiple times to create multiple records
	CreateCompany(related CompanyData) QueueJobData
	// CreateDate returns the value of the CreateDate field.
	// If this CreateDate is not set in this QueueJobData, then
	// the Go zero value for the type is returned.
	CreateDate() dates.DateTime
	// HasCreateDate returns true if CreateDate is set in this QueueJobData
	HasCreateDate() bool
	// SetCreateDate sets the CreateDate field with the given value.
	// It returns this QueueJobData so that calls can be chained.
	SetCreateDate(value dates.DateTime) QueueJobData
	// UnsetCreateDate removes the value of the CreateDate field if it exists.
	// It returns this QueueJobData so that calls can be chained.
	UnsetCreateDate() QueueJobData

	// CreateUID returns the value of the CreateUID field.
	// If this CreateUID is not set in this QueueJobData, then
	// the Go zero value for the type is returned.
	CreateUID() int64
	// HasCreateUID returns true if CreateUID is set in this QueueJobData
	HasCreateUID() bool
	// SetCreateUID sets the CreateUID field with the given value.
	// It returns this QueueJobData so that calls can be chained.
	SetCreateUID(value int64) QueueJobData
	// UnsetCreateUID removes the value of the CreateUID field if it exists.
	// It returns this QueueJobData so that calls can be chained.
	UnsetCreateUID() QueueJobData

	// DateDone returns the value of the DateDone field.
	// If this DateDone is not set in this QueueJobData, then
	// the Go zero value for the type is returned.
	DateDone() dates.DateTime
	// HasDateDone returns true if DateDone is set in this QueueJobData
	HasDateDone() bool
	// SetDateDone sets the DateDone field with the given value.
	// It returns this QueueJobData so that calls can be chained.
	SetDateDone(value dates.DateTime) QueueJobData
	// UnsetDateDone removes the value of the DateDone field if it exists.
	// It returns this QueueJobData so that calls can be chained.
	UnsetDateDone() QueueJobData

	// DateEnqueued returns the value of the DateEnqueued field.
	// If this DateEnqueued is not set in this QueueJobData, then
	// the Go zero value for the type is returned.
	DateEnqueued() dates.DateTime
	// HasDateEnqueued returns true if DateEnqueued is set in this QueueJobData
	HasDateEnqueued() bool
	// SetDateEnqueued sets the DateEnqueued field with the given value.
	// It returns this QueueJobData so that calls can be chained.
	SetDateEnqueued(value dates.DateTime) QueueJobData
	// UnsetDateEnqueued removes the value of the DateEnqueued field if it exists.
	// It returns this QueueJobData so that calls can be chained.
	UnsetDateEnqueued() QueueJobData

	// DateStarted returns the value of the DateStarted field.
	// If this DateStarted is not set in this QueueJobData, then
	// the Go zero value for the type is returned.
	DateStarted() dates.DateTime
	// HasDateStarted returns true if DateStarted is set in this QueueJobData
	HasDateStarted() bool
	// SetDateStarted sets the DateStarted field with the given value.
	// It returns this QueueJobData so that calls can be chained.
	SetDateStarted(value dates.DateTime) QueueJobData
	// UnsetDateStarted removes the value of the DateStarted field if it exists.
	// It returns this QueueJobData so that calls can be chained.
	UnsetDateStarted() QueueJobData

	// DisplayName returns the value of the DisplayName field.
	// If this DisplayName is not set in this QueueJobData, then
	// the Go zero value for the type is returned.
	DisplayName() string
	// HasDisplayName returns true if DisplayName is set in this QueueJobData
	HasDisplayName() bool
	// SetDisplayName sets the DisplayName field with the given value.
	// It returns this QueueJobData so that calls can be chained.
	SetDisplayName(value string) QueueJobData
	// UnsetDisplayName removes the value of the DisplayName field if it exists.
	// It returns this QueueJobData so that calls can be chained.
	UnsetDisplayName() QueueJobData

	// ETA returns the value of the ETA field.
	// If this ETA is not set in this QueueJobData, then
	// the Go zero value for the type is returned.
	ETA() dates.DateTime
	// HasETA returns true if ETA is set in this QueueJobData
	HasETA() bool
	// SetETA sets the ETA field with the given value.
	// It returns this QueueJobData so that calls can be chained.
	SetETA(value dates.DateTime) QueueJobData
	// UnsetETA removes the value of the ETA field if it exists.
	// It returns this QueueJobData so that calls can be chained.
	UnsetETA() QueueJobData

	// ExcInfo returns the value of the ExcInfo field.
	// If this ExcInfo is not set in this QueueJobData, then
	// the Go zero value for the type is returned.
	ExcInfo() string
	// HasExcInfo returns true if ExcInfo is set in this QueueJobData
	HasExcInfo() bool
	// SetExcInfo sets the ExcInfo field with the given value.
	// It returns this QueueJobData so that calls can be chained.
	SetExcInfo(value string) QueueJobData
	// UnsetExcInfo removes the value of the ExcInfo field if it exists.
	// It returns this QueueJobData so that calls can be chained.
	UnsetExcInfo() QueueJobData

	// ExecuteAfterJob returns the value of the ExecuteAfterJob field.
	// If this ExecuteAfterJob is not set in this QueueJobData, then
	// the Go zero value for the type is returned.
	ExecuteAfterJob() QueueJobSet
	// HasExecuteAfterJob returns true if ExecuteAfterJob is set in this QueueJobData
	HasExecuteAfterJob() bool
	// SetExecuteAfterJob sets the ExecuteAfterJob field with the given value.
	// It returns this QueueJobData so that calls can be chained.
	SetExecuteAfterJob(value QueueJobSet) QueueJobData
	// UnsetExecuteAfterJob removes the value of the ExecuteAfterJob field if it exists.
	// It returns this QueueJobData so that calls can be chained.
	UnsetExecuteAfterJob() QueueJobData

	// CreateExecuteAfterJob stores the related QueueJobData to be used to create
	// a related record on the fly for ExecuteAfterJob.
	//
	// This method can be called multiple times to create multiple records
	CreateExecuteAfterJob(related QueueJobData) QueueJobData
	// ExecuteBeforeJobs returns the value of the ExecuteBeforeJobs field.
	// If this ExecuteBeforeJobs is not set in this QueueJobData, then
	// the Go zero value for the type is returned.
	ExecuteBeforeJobs() QueueJobSet
	// HasExecuteBeforeJobs returns true if ExecuteBeforeJobs is set in this QueueJobData
	HasExecuteBeforeJobs() bool
	// SetExecuteBeforeJobs sets the ExecuteBeforeJobs field with the given value.
	// It returns this QueueJobData so that calls can be chained.
	SetExecuteBeforeJobs(value QueueJobSet) QueueJobData
	// UnsetExecuteBeforeJobs removes the value of the ExecuteBeforeJobs field if it exists.
	// It returns this QueueJobData so that calls can be chained.
	UnsetExecuteBeforeJobs() QueueJobData

	// CreateExecuteBeforeJobs stores the related QueueJobData to be used to create
	// a related record on the fly for ExecuteBeforeJobs.
	//
	// This method can be called multiple times to create multiple records
	CreateExecuteBeforeJobs(related QueueJobData) QueueJobData
	// HexyaExternalID returns the value of the HexyaExternalID field.
	// If this HexyaExternalID is not set in this QueueJobData, then
	// the Go zero value for the type is returned.
	HexyaExternalID() string
	// HasHexyaExternalID returns true if HexyaExternalID is set in this QueueJobData
	HasHexyaExternalID() bool
	// SetHexyaExternalID sets the HexyaExternalID field with the given value.
	// It returns this QueueJobData so that calls can be chained.
	SetHexyaExternalID(value string) QueueJobData
	// UnsetHexyaExternalID removes the value of the HexyaExternalID field if it exists.
	// It returns this QueueJobData so that calls can be chained.
	UnsetHexyaExternalID() QueueJobData

	// HexyaVersion returns the value of the HexyaVersion field.
	// If this HexyaVersion is not set in this QueueJobData, then
	// the Go zero value for the type is returned.
	HexyaVersion() int
	// HasHexyaVersion returns true if HexyaVersion is set in this QueueJobData
	HasHexyaVersion() bool
	// SetHexyaVersion sets the HexyaVersion field with the given value.
	// It returns this QueueJobData so that calls can be chained.
	SetHexyaVersion(value int) QueueJobData
	// UnsetHexyaVersion removes the value of the HexyaVersion field if it exists.
	// It returns this QueueJobData so that calls can be chained.
	UnsetHexyaVersion() QueueJobData

	// ID returns the value of the ID field.
	// If this ID is not set in this QueueJobData, then
	// the Go zero value for the type is returned.
	ID() int64
	// HasID returns true if ID is set in this QueueJobData
	HasID() bool
	// SetID sets the ID field with the given value.
	// It returns this QueueJobData so that calls can be chained.
	SetID(value int64) QueueJobData
	// UnsetID removes the value of the ID field if it exists.
	// It returns this QueueJobData so that calls can be chained.
	UnsetID() QueueJobData

	// LastUpdate returns the value of the LastUpdate field.
	// If this LastUpdate is not set in this QueueJobData, then
	// the Go zero value for the type is returned.
	LastUpdate() dates.DateTime
	// HasLastUpdate returns true if LastUpdate is set in this QueueJobData
	HasLastUpdate() bool
	// SetLastUpdate sets the LastUpdate field with the given value.
	// It returns this QueueJobData so that calls can be chained.
	SetLastUpdate(value dates.DateTime) QueueJobData
	// UnsetLastUpdate removes the value of the LastUpdate field if it exists.
	// It returns this QueueJobData so that calls can be chained.
	UnsetLastUpdate() QueueJobData

	// MaxRetries returns the value of the MaxRetries field.
	// If this MaxRetries is not set in this QueueJobData, then
	// the Go zero value for the type is returned.
	MaxRetries() int64
	// HasMaxRetries returns true if MaxRetries is set in this QueueJobData
	HasMaxRetries() bool
	// SetMaxRetries sets the MaxRetries field with the given value.
	// It returns this QueueJobData so that calls can be chained.
	SetMaxRetries(value int64) QueueJobData
	// UnsetMaxRetries removes the value of the MaxRetries field if it exists.
	// It returns this QueueJobData so that calls can be chained.
	UnsetMaxRetries() QueueJobData

	// Method returns the value of the Method field.
	// If this Method is not set in this QueueJobData, then
	// the Go zero value for the type is returned.
	Method() string
	// HasMethod returns true if Method is set in this QueueJobData
	HasMethod() bool
	// SetMethod sets the Method field with the given value.
	// It returns this QueueJobData so that calls can be chained.
	SetMethod(value string) QueueJobData
	// UnsetMethod removes the value of the Method field if it exists.
	// It returns this QueueJobData so that calls can be chained.
	UnsetMethod() QueueJobData

	// Model returns the value of the Model field.
	// If this Model is not set in this QueueJobData, then
	// the Go zero value for the type is returned.
	Model() string
	// HasModel returns true if Model is set in this QueueJobData
	HasModel() bool
	// SetModel sets the Model field with the given value.
	// It returns this QueueJobData so that calls can be chained.
	SetModel(value string) QueueJobData
	// UnsetModel removes the value of the Model field if it exists.
	// It returns this QueueJobData so that calls can be chained.
	UnsetModel() QueueJobData

	// Name returns the value of the Name field.
	// If this Name is not set in this QueueJobData, then
	// the Go zero value for the type is returned.
	Name() string
	// HasName returns true if Name is set in this QueueJobData
	HasName() bool
	// SetName sets the Name field with the given value.
	// It returns this QueueJobData so that calls can be chained.
	SetName(value string) QueueJobData
	// UnsetName removes the value of the Name field if it exists.
	// It returns this QueueJobData so that calls can be chained.
	UnsetName() QueueJobData

	// Priority returns the value of the Priority field.
	// If this Priority is not set in this QueueJobData, then
	// the Go zero value for the type is returned.
	Priority() int64
	// HasPriority returns true if Priority is set in this QueueJobData
	HasPriority() bool
	// SetPriority sets the Priority field with the given value.
	// It returns this QueueJobData so that calls can be chained.
	SetPriority(value int64) QueueJobData
	// UnsetPriority removes the value of the Priority field if it exists.
	// It returns this QueueJobData so that calls can be chained.
	UnsetPriority() QueueJobData

	// RecordsIds returns the value of the RecordsIds field.
	// If this RecordsIds is not set in this QueueJobData, then
	// the Go zero value for the type is returned.
	RecordsIds() string
	// HasRecordsIds returns true if RecordsIds is set in this QueueJobData
	HasRecordsIds() bool
	// SetRecordsIds sets the RecordsIds field with the given value.
	// It returns this QueueJobData so that calls can be chained.
	SetRecordsIds(value string) QueueJobData
	// UnsetRecordsIds removes the value of the RecordsIds field if it exists.
	// It returns this QueueJobData so that calls can be chained.
	UnsetRecordsIds() QueueJobData

	// Result returns the value of the Result field.
	// If this Result is not set in this QueueJobData, then
	// the Go zero value for the type is returned.
	Result() string
	// HasResult returns true if Result is set in this QueueJobData
	HasResult() bool
	// SetResult sets the Result field with the given value.
	// It returns this QueueJobData so that calls can be chained.
	SetResult(value string) QueueJobData
	// UnsetResult removes the value of the Result field if it exists.
	// It returns this QueueJobData so that calls can be chained.
	UnsetResult() QueueJobData

	// Retry returns the value of the Retry field.
	// If this Retry is not set in this QueueJobData, then
	// the Go zero value for the type is returned.
	Retry() int64
	// HasRetry returns true if Retry is set in this QueueJobData
	HasRetry() bool
	// SetRetry sets the Retry field with the given value.
	// It returns this QueueJobData so that calls can be chained.
	SetRetry(value int64) QueueJobData
	// UnsetRetry removes the value of the Retry field if it exists.
	// It returns this QueueJobData so that calls can be chained.
	UnsetRetry() QueueJobData

	// State returns the value of the State field.
	// If this State is not set in this QueueJobData, then
	// the Go zero value for the type is returned.
	State() string
	// HasState returns true if State is set in this QueueJobData
	HasState() bool
	// SetState sets the State field with the given value.
	// It returns this QueueJobData so that calls can be chained.
	SetState(value string) QueueJobData
	// UnsetState removes the value of the State field if it exists.
	// It returns this QueueJobData so that calls can be chained.
	UnsetState() QueueJobData

	// User returns the value of the User field.
	// If this User is not set in this QueueJobData, then
	// the Go zero value for the type is returned.
	User() UserSet
	// HasUser returns true if User is set in this QueueJobData
	HasUser() bool
	// SetUser sets the User field with the given value.
	// It returns this QueueJobData so that calls can be chained.
	SetUser(value UserSet) QueueJobData
	// UnsetUser removes the value of the User field if it exists.
	// It returns this QueueJobData so that calls can be chained.
	UnsetUser() QueueJobData

	// CreateUser stores the related UserData to be used to create
	// a related record on the fly for User.
	//
	// This method can be called multiple times to create multiple records
	CreateUser(related UserData) QueueJobData
	// WriteDate returns the value of the WriteDate field.
	// If this WriteDate is not set in this QueueJobData, then
	// the Go zero value for the type is returned.
	WriteDate() dates.DateTime
	// HasWriteDate returns true if WriteDate is set in this QueueJobData
	HasWriteDate() bool
	// SetWriteDate sets the WriteDate field with the given value.
	// It returns this QueueJobData so that calls can be chained.
	SetWriteDate(value dates.DateTime) QueueJobData
	// UnsetWriteDate removes the value of the WriteDate field if it exists.
	// It returns this QueueJobData so that calls can be chained.
	UnsetWriteDate() QueueJobData

	// WriteUID returns the value of the WriteUID field.
	// If this WriteUID is not set in this QueueJobData, then
	// the Go zero value for the type is returned.
	WriteUID() int64
	// HasWriteUID returns true if WriteUID is set in this QueueJobData
	HasWriteUID() bool
	// SetWriteUID sets the WriteUID field with the given value.
	// It returns this QueueJobData so that calls can be chained.
	SetWriteUID(value int64) QueueJobData
	// UnsetWriteUID removes the value of the WriteUID field if it exists.
	// It returns this QueueJobData so that calls can be chained.
	UnsetWriteUID() QueueJobData
}

// A QueueJobGroupAggregateRow holds a row of results of a query with a group by clause
type QueueJobGroupAggregateRow interface {
	// Values() returns the values of the actual query
	Values() QueueJobData
	// Count is the number of lines aggregated into this one
	Count() int
	// Condition can be used to query the aggregated rows separately if needed
	Condition() q.QueueJobCondition
}
