// This file is autogenerated by hexya-generate
// DO NOT MODIFY THIS FILE - ANY CHANGES WILL BE OVERWRITTEN

package m

import (
	"github.com/beevik/etree"
	"github.com/hexya-addons/web/domains"
	"github.com/hexya-addons/web/webtypes"
	"github.com/hexya-erp/hexya/src/actions"
	"github.com/hexya-erp/hexya/src/models"
	"github.com/hexya-erp/hexya/src/models/operator"
	"github.com/hexya-erp/hexya/src/models/types"
	"github.com/hexya-erp/hexya/src/models/types/dates"
	"github.com/hexya-erp/pool/q"
)

// SequenceSet is an autogenerated type to handle Sequence objects.
type SequenceSet interface {
	models.RecordSet
	// SequenceSetHexyaFunc is a dummy function to uniquely match interfaces.
	SequenceSetHexyaFunc()
	// ForceLoad reloads the cache for the given fields and updates the ids of this SequenceSet.
	//
	// If no fields are given, all DB columns of the Sequence model are retrieved.
	//
	// It also returns this SequenceSet.
	ForceLoad(fields ...models.FieldName) SequenceSet
	// Active is a getter for the value of the "Active" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	Active() bool
	// SetActive is a setter for the value of the "Active" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetActive panics if the RecordSet is empty.
	SetActive(value bool)
	// Code is a getter for the value of the "Code" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	Code() string
	// SetCode is a setter for the value of the "Code" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetCode panics if the RecordSet is empty.
	SetCode(value string)
	// Company is a getter for the value of the "Company" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	Company() CompanySet
	// SetCompany is a setter for the value of the "Company" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetCompany panics if the RecordSet is empty.
	SetCompany(value CompanySet)
	// CreateDate is a getter for the value of the "CreateDate" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	CreateDate() dates.DateTime
	// SetCreateDate is a setter for the value of the "CreateDate" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetCreateDate panics if the RecordSet is empty.
	SetCreateDate(value dates.DateTime)
	// CreateUID is a getter for the value of the "CreateUID" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	CreateUID() int64
	// SetCreateUID is a setter for the value of the "CreateUID" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetCreateUID panics if the RecordSet is empty.
	SetCreateUID(value int64)
	// DateRanges is a getter for the value of the "DateRanges" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	DateRanges() SequenceDateRangeSet
	// SetDateRanges is a setter for the value of the "DateRanges" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetDateRanges panics if the RecordSet is empty.
	SetDateRanges(value SequenceDateRangeSet)
	// DisplayName is a getter for the value of the "DisplayName" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	DisplayName() string
	// SetDisplayName is a setter for the value of the "DisplayName" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetDisplayName panics if the RecordSet is empty.
	SetDisplayName(value string)
	// HexyaExternalID is a getter for the value of the "HexyaExternalID" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	HexyaExternalID() string
	// SetHexyaExternalID is a setter for the value of the "HexyaExternalID" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetHexyaExternalID panics if the RecordSet is empty.
	SetHexyaExternalID(value string)
	// HexyaVersion is a getter for the value of the "HexyaVersion" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	HexyaVersion() int
	// SetHexyaVersion is a setter for the value of the "HexyaVersion" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetHexyaVersion panics if the RecordSet is empty.
	SetHexyaVersion(value int)
	// ID is a getter for the value of the "ID" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	ID() int64
	// SetID is a setter for the value of the "ID" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetID panics if the RecordSet is empty.
	SetID(value int64)
	// Implementation is a getter for the value of the "Implementation" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	Implementation() string
	// SetImplementation is a setter for the value of the "Implementation" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetImplementation panics if the RecordSet is empty.
	SetImplementation(value string)
	// LastUpdate is a getter for the value of the "LastUpdate" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	LastUpdate() dates.DateTime
	// SetLastUpdate is a setter for the value of the "LastUpdate" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetLastUpdate panics if the RecordSet is empty.
	SetLastUpdate(value dates.DateTime)
	// Name is a getter for the value of the "Name" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	Name() string
	// SetName is a setter for the value of the "Name" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetName panics if the RecordSet is empty.
	SetName(value string)
	// NumberIncrement is a getter for the value of the "NumberIncrement" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	NumberIncrement() int64
	// SetNumberIncrement is a setter for the value of the "NumberIncrement" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetNumberIncrement panics if the RecordSet is empty.
	SetNumberIncrement(value int64)
	// NumberNext is a getter for the value of the "NumberNext" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	NumberNext() int64
	// SetNumberNext is a setter for the value of the "NumberNext" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetNumberNext panics if the RecordSet is empty.
	SetNumberNext(value int64)
	// NumberNextActual is a getter for the value of the "NumberNextActual" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	NumberNextActual() int64
	// SetNumberNextActual is a setter for the value of the "NumberNextActual" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetNumberNextActual panics if the RecordSet is empty.
	SetNumberNextActual(value int64)
	// Padding is a getter for the value of the "Padding" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	Padding() int64
	// SetPadding is a setter for the value of the "Padding" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetPadding panics if the RecordSet is empty.
	SetPadding(value int64)
	// Prefix is a getter for the value of the "Prefix" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	Prefix() string
	// SetPrefix is a setter for the value of the "Prefix" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetPrefix panics if the RecordSet is empty.
	SetPrefix(value string)
	// Suffix is a getter for the value of the "Suffix" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	Suffix() string
	// SetSuffix is a setter for the value of the "Suffix" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetSuffix panics if the RecordSet is empty.
	SetSuffix(value string)
	// UseDateRange is a getter for the value of the "UseDateRange" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	UseDateRange() bool
	// SetUseDateRange is a setter for the value of the "UseDateRange" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetUseDateRange panics if the RecordSet is empty.
	SetUseDateRange(value bool)
	// WriteDate is a getter for the value of the "WriteDate" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	WriteDate() dates.DateTime
	// SetWriteDate is a setter for the value of the "WriteDate" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetWriteDate panics if the RecordSet is empty.
	SetWriteDate(value dates.DateTime)
	// WriteUID is a getter for the value of the "WriteUID" field of the first
	// record in this RecordSet. It returns the Go zero value if the RecordSet is empty.
	WriteUID() int64
	// SetWriteUID is a setter for the value of the "WriteUID" field of this
	// RecordSet. All Records of this RecordSet will be updated. Each call to this
	// method makes an update query in the database.
	//
	// SetWriteUID panics if the RecordSet is empty.
	SetWriteUID(value int64)
	// ActionArchive sets Active=false on a recordset, by calling ToggleActive to take the
	// corresponding actions according to the model
	ActionArchive()
	// ActionUnarchive sets Active=true on a recordset, by calling ToggleActive to take the
	// corresponding actions according to the model
	ActionUnarchive()
	// AddDomainLimitOffset adds the given domain, limit, offset
	// and order to the current RecordSet query.
	AddDomainLimitOffset(domain domains.Domain, limit int, offset int, order string) SequenceSet
	// AddModifiers adds the modifiers attribute nodes to given xml doc.
	AddModifiers(doc *etree.Document, fieldInfos map[string]*models.FieldInfo)
	// AddNameToRelations returns the given RecordData after getting the name of all 2one relation ids
	AddNamesToRelations(data models.RecordData, fInfos map[string]*models.FieldInfo) models.RecordData

	Aggregates(fieldNames ...models.FieldName) []SequenceGroupAggregateRow
	// AlterHexyaSequence alters the DB sequence that backs this sequence
	AlterHexyaSequence(numberIncrement int64, numberNext int64)
	// Browse returns a new RecordSet with only the records with the given ids.
	// Note that this function is just a shorcut for Search on a list of ids.
	Browse(ids []int64) SequenceSet
	// BrowseOne returns a new RecordSet with only the record with the given id.
	// Note that this function is just a shorcut for Search on a given id.
	BrowseOne(id int64) SequenceSet

	CartesianProduct(others ...SequenceSet) []SequenceSet
	// CheckAccessRights verifies that the operation given by "operation" is allowed for
	// the current user according to the access rights.
	//
	// operation must be one of "read", "create", "unlink", "write".
	CheckAccessRights(args webtypes.CheckAccessRightsArgs) bool
	// CheckExecutionPermission panics if the current user is not allowed to execute the given method.
	//
	// If dontPanic is false, this function will panic, otherwise it returns true
	// if the user has the execution permission and false otherwise.
	CheckExecutionPermission(method *models.Method, dontPanic ...bool) bool
	// CheckRecursion verifies that there is no loop in a hierarchical structure of records,
	// by following the parent relationship using the 'Parent' field until a loop is detected or
	// until a top-level record is found.
	//
	// It returns true if no loop was found, false otherwise`,
	CheckRecursion() bool
	// ComputeDisplayName updates the DisplayName field with the result of NameGet
	ComputeDisplayName() *models.ModelData
	// ComputeLastUpdate returns the last datetime at which the record has been updated.
	ComputeLastUpdate() *models.ModelData
	// ComputeNumberNextActual returns the real next number for the sequence depending on the implementation
	ComputeNumberNextActual() SequenceData

	Copy(overrides SequenceData) SequenceSet

	CopyData(overrides SequenceData) SequenceData

	Create(data SequenceData) SequenceSet
	// CreateDateRangeSeq creates the date range for the given date
	CreateDateRangeSeq(date dates.Date) SequenceDateRangeSet

	DefaultGet() SequenceData
	// Enqueue queues the execution of the given method with the given arguments on this recordset.
	// description will be the name given to the job.
	Enqueue(description string, method models.Methoder, arguments ...interface{}) QueueJobSet
	// Equals returns true if this RecordSet is the same as other
	// i.e. they are of the same model and have the same ids
	Equals(other SequenceSet) bool
	// ExecuteO2MActions executes the actions on one2many fields given by
	// the list of triplets received from the client
	ExecuteO2MActions(fieldName models.FieldName, info *models.FieldInfo, value interface{}) interface{}
	// Fetch query the database with the current filter and returns a RecordSet
	// with the queries ids.
	//
	// Fetch is lazy and only return ids. Use Load() instead if you want to fetch all fields.
	Fetch() SequenceSet
	// FieldGet returns the definition of the given field.
	// The string, help, and selection (if present) attributes are translated.
	FieldGet(field models.FieldName) *models.FieldInfo
	// FieldsGet returns the definition of each field.
	// The embedded fields are included.
	// The string, help, and selection (if present) attributes are translated.
	//
	// The result map is indexed by the fields JSON names.
	FieldsGet(args models.FieldsGetArgs) map[string]*models.FieldInfo
	// FieldsViewGet is the base implementation of the 'FieldsViewGet' method which
	// gets the detailed composition of the requested view like fields, mixin,
	// view architecture.
	FieldsViewGet(args webtypes.FieldsViewGetParams) *webtypes.FieldsViewData

	Filtered(test func(SequenceSet) bool) SequenceSet
	// FormatRelationFields returns the given data with all relation fields converted to int64 or []int64
	FormatRelationFields(data models.RecordData, fInfos map[string]*models.FieldInfo) models.RecordData
	// GetFormviewAction returns an action to open the document.
	// This method is meant to be overridden in addons that want
	// to give specific view ids for example.`,
	GetFormviewAction() *actions.Action
	// GetFormviewID returns an view id to open the document with.
	// This method is meant to be overridden in addons that want
	// to give specific view ids for example.
	GetFormviewId() string
	// GetNextChar returns the given number formatted as per the sequence data
	GetNextChar(numberNext int64) string
	// GetRecord returns the Recordset with the given externalID. It panics if the externalID does not exist.
	GetRecord(externalID string) SequenceSet
	// GetToolbar returns a toolbar populated with the actions linked to this model
	GetToolbar() webtypes.Toolbar
	// GroupBy returns a new RecordSet grouped with the given GROUP BY expressions.
	GroupBy(exprs ...models.FieldName) SequenceSet
	// Intersect returns a new RecordCollection with only the records that are both
	// in this RecordCollection and in the other RecordSet.
	Intersect(other SequenceSet) SequenceSet
	// InverseNumberNextActual is the setter function for the NumberNextActual field
	InverseNumberNextActual(value int64)
	// Limit returns a new RecordSet with only the first 'limit' records.
	Limit(limit int) SequenceSet
	// Load looks up cache for fields of the RecordCollection and
	// query database for missing values.
	// fields are the fields to retrieve in the expression format,
	// i.e. "User.Profile.Age" or "user_id.profile_id.age".
	// If no fields are given, all DB columns of the RecordCollection's
	// model are retrieved.
	Load(fields ...models.FieldName) SequenceSet
	// LoadViews returns the data for all the views and filters required in the parameters.
	LoadViews(args webtypes.LoadViewsArgs) *webtypes.LoadViewsData
	// ManageGroupsOnFields adds the invisible attribute to fields nodes if the current
	// user does not belong to one of the groups of the 'groups' attribute
	ManageGroupsOnFields(doc *etree.Document, fieldInfos map[string]*models.FieldInfo)
	// NameGet retrieves the human readable name of this record.`,
	NameGet() string
	// NameSearch searches for records that have a display name matching the given
	// "name" pattern when compared with the given "operator", while also
	// matching the optional search domain ("args").
	//
	// This is used for example to provide suggestions based on a partial
	// value for a relational field. Sometimes be seen as the inverse
	// function of NameGet but it is not guaranteed to be.
	NameSearch(params webtypes.NameSearchParams) []webtypes.RecordIDWithName

	New(data SequenceData) SequenceSet
	// Next returns the next number (formatted) in the preferred sequence in all the ones given in self
	Next() string
	// NextByCode draws an interpolated string using a sequence with the requested code.
	// If several sequences with the correct code are available to the user
	// (multi-company cases), the one from the user's current company will be used.
	//
	// The context may contain a 'force_company' key with the ID of the company to
	// use instead of the user's current company for the sequence selection.
	// A matching sequence for that specific company will get higher priority
	NextByCode(sequenceCode string) string
	// NextByID draws an interpolated string using the specified sequence.
	NextByID() string
	// NextDo returns the next sequence number formatted
	NextDo() string
	// NormalizeM2MData converts the list of triplets received from the client into the final list of ids
	// to keep in the Many2Many relationship of this model through the given field.
	NormalizeM2MData(fieldName models.FieldName, info *models.FieldInfo, value interface{}) interface{}
	// Offset returns a new RecordSet with only the records starting at offset
	Offset(offset int) SequenceSet
	// Onchange returns the values that must be modified according to each field's Onchange
	// method in the pseudo-record given as params.Values`,
	Onchange(params models.OnchangeParams) models.OnchangeResult
	// OrderBy returns a new RecordSet ordered by the given ORDER BY expressions.
	// Each expression contains a field name and optionally one of "asc" or "desc", such as:
	//
	// rs.OrderBy("Company", "Name desc")
	OrderBy(exprs ...string) SequenceSet
	// PostProcessCreateValues updates FK of related records created at the same time.
	//
	// This method is meant to be called with the second returned value of ProcessCreateValues
	// after record creation.
	PostProcessCreateValues(data models.RecordData)
	// PostProcessFilters transforms a map[models.FieldName]models.Conditioner
	// in a map[string][]interface{} which acts as a map of domains.
	PostProcessFilters(in map[models.FieldName]models.Conditioner) map[string][]interface{}
	// ProcessCreateValues updates the given data values for Create method to be
	// compatible with the ORM, in particular for relation fields.
	//
	// It returns a first FieldMap to be used as argument to the Create method, and
	// a second map to be used with a subsequent call to PostProcessCreateValues (for
	// updating FKs pointing to the newly created record).
	ProcessCreateValues(data models.RecordData) (models.RecordData, models.RecordData)
	// ProcessElementAttrs returns a modifiers map according to the domain
	// in attrs of the given element
	ProcessElementAttrs(element *etree.Element, fieldInfos map[string]*models.FieldInfo) map[string]interface{}
	// ProcessFieldElementModifiers modifies the given modifiers map by taking into account:
	// - 'invisible', 'readonly' and 'required' attributes in field tags
	// - 'ReadOnly' and 'Required' parameters of the model's field'
	// It returns the modified map.
	ProcessFieldElementModifiers(element *etree.Element, fieldInfos map[string]*models.FieldInfo, modifiers map[string]interface{}) map[string]interface{}
	// ProcessView makes all the necessary modifications to the view
	// arch and returns the new xml string.`,
	ProcessView(arch *etree.Document, fieldInfos map[string]*models.FieldInfo) string
	// ProcessWriteValues updates the given data values for Write method to be
	// compatible with the ORM, in particular for relation fields
	ProcessWriteValues(data models.RecordData) models.RecordData
	// Read reads the database and returns a slice of FieldMap of the given model.
	Read(fields models.FieldNames) []models.RecordData
	// ReadGroup gets a list of record aggregates according to the given parameters.
	ReadGroup(params webtypes.ReadGroupParams) []models.FieldMap
	// SQLFromCondition returns the WHERE clause sql and arguments corresponding to
	// the given condition.`,
	SQLFromCondition(c *models.Condition) (string, models.SQLParams)

	Search(condition q.SequenceCondition) SequenceSet
	// SearchAll returns a RecordSet with all items of the table, regardless of the
	// current RecordSet query. It is mainly meant to be used on an empty RecordSet.
	SearchAll() SequenceSet

	SearchByName(name string, op operator.Operator, additionalCond q.SequenceCondition, limit int) SequenceSet
	// SearchCount fetch from the database the number of records that match the RecordSet conditions.
	SearchCount() int
	// SearchDomain execute a search on the given domain.
	SearchDomain(domain domains.Domain) CommonMixinSet
	// SearchRead retrieves database records according to the filters defined in params.
	SearchRead(params webtypes.SearchParams) []models.RecordData

	Sorted(less func(SequenceSet, SequenceSet) bool) SequenceSet
	// SortedByField returns a new record set with the same records as rc but sorted by the given field.
	// If reverse is true, the sort is done in reversed order
	SortedByField(namer models.FieldName, reverse bool) SequenceSet
	// SortedDefault returns a new record set with the same records as rc but sorted according
	// to the default order of this model
	SortedDefault() SequenceSet
	// Subtract returns a RecordSet with the Records that are in this
	// RecordCollection but not in the given 'other' one.
	// The result is guaranteed to be a set of unique records.
	Subtract(other SequenceSet) SequenceSet
	// Sudo returns a new RecordSet with the given userID
	// or the superuser ID if not specified
	Sudo(userID ...int64) SequenceSet
	// ToggleActive toggles the Active field of this object if it exists.
	ToggleActive()
	// Union returns a new RecordSet that is the union of this RecordSet and the given
	// "other" RecordSet. The result is guaranteed to be a set of unique records.
	Union(other SequenceSet) SequenceSet
	// Unlink deletes the given records in the database.
	Unlink() int64
	// UpdateNoGap gets the next number of a "No Gap" sequence
	UpdateNoGap() int64
	// WebReadGroup returns the result of a read_group (and optionally search for and read records inside each
	// group), and the total number of groups matching the search domain.
	WebReadGroup(params webtypes.WebReadGroupParams) webtypes.WebReadGroupResult
	// WebReadGroupPrivate performs a read_group and optionally a web_search_read for each group.
	WebReadGroupPrivate(params webtypes.WebReadGroupParams) []models.FieldMap
	// WebSearchRead performs a search_read and a search_count.
	WebSearchRead(params webtypes.SearchParams) webtypes.SearchReadResult
	// WithContext returns a copy of the current RecordSet with
	// its context extended by the given key and value.
	WithContext(key string, value interface{}) SequenceSet
	// WithEnv returns a copy of the current RecordSet with the given Environment.
	WithEnv(env models.Environment) SequenceSet
	// WithNewContext returns a copy of the current RecordSet with its context
	// replaced by the given one.
	WithNewContext(context *types.Context) SequenceSet

	Write(data SequenceData) bool
	// Super returns a RecordSet with a modified callstack so that call to the current
	// method will execute the next method layer.
	//
	// This method is meant to be used inside a method layer function to call its parent,
	// such as:
	//
	//    func (rs h.MyRecordSet) MyMethod() string {
	//        res := rs.Super().MyMethod()
	//        res += " ok!"
	//        return res
	//    }
	//
	// Calls to a different method than the current method will call its next layer only
	// if the current method has been called from a layer of the other method. Otherwise,
	// it will be the same as calling the other method directly.
	Super() SequenceSet
	// ModelData returns a new SequenceData object populated with the values
	// of the given FieldMap.
	ModelData(fMap models.FieldMap) SequenceData
	// Records returns a slice with all the records of this RecordSet, as singleton RecordSets
	Records() []SequenceSet
	// First returns the values of the first Record of the RecordSet as a pointer to a SequenceData.
	//
	// If this RecordSet is empty, it returns an empty SequenceData.
	First() SequenceData
	// All returns the values of all Records of the RecordCollection as a slice of SequenceData pointers.
	All() []SequenceData
}

// SequenceData is used to hold values of an Sequence object instance
// when creating or updating a SequenceSet.
type SequenceData interface {
	models.RecordData
	// Get returns the value of the given field.
	//
	// The field can be either its name or is JSON name.
	Get(field models.FieldName) interface{}
	// Has returns true if a value is set for the given field.
	//
	// The field can be either its name or is JSON name.
	Has(field models.FieldName) bool
	// Set sets the given field with the given value.
	// If the field already exists, then it is updated with value.
	// Otherwise, a new entry is inserted.
	//
	// It returns the given SequenceData so that calls can be chained
	Set(field models.FieldName, value interface{}) SequenceData
	// Unset removes the value of the given field if it exists.
	//
	// It returns the given ModelData so that calls can be chained
	Unset(field models.FieldName) SequenceData
	// Copy returns a copy of this SequenceData
	Copy() SequenceData
	// MergeWith updates this SequenceData with the given other SequenceData
	// If a field of the other SequenceData already exists here, the value is overridden,
	// otherwise, the field is inserted.
	MergeWith(other SequenceData)
	// Keys returns the SequenceData keys as a slice of strings
	Keys() (res []string)
	// OrderedKeys returns the keys of this SequenceData ordered.
	//
	// This has the convenient side effect of having shorter paths come before longer paths,
	// which is particularly useful when creating or updating related records.
	OrderedKeys() []string
	// FieldNames returns the SequenceData keys as a slice of FieldNames.
	FieldNames() models.FieldNames
	// Active returns the value of the Active field.
	// If this Active is not set in this SequenceData, then
	// the Go zero value for the type is returned.
	Active() bool
	// HasActive returns true if Active is set in this SequenceData
	HasActive() bool
	// SetActive sets the Active field with the given value.
	// It returns this SequenceData so that calls can be chained.
	SetActive(value bool) SequenceData
	// UnsetActive removes the value of the Active field if it exists.
	// It returns this SequenceData so that calls can be chained.
	UnsetActive() SequenceData

	// Code returns the value of the Code field.
	// If this Code is not set in this SequenceData, then
	// the Go zero value for the type is returned.
	Code() string
	// HasCode returns true if Code is set in this SequenceData
	HasCode() bool
	// SetCode sets the Code field with the given value.
	// It returns this SequenceData so that calls can be chained.
	SetCode(value string) SequenceData
	// UnsetCode removes the value of the Code field if it exists.
	// It returns this SequenceData so that calls can be chained.
	UnsetCode() SequenceData

	// Company returns the value of the Company field.
	// If this Company is not set in this SequenceData, then
	// the Go zero value for the type is returned.
	Company() CompanySet
	// HasCompany returns true if Company is set in this SequenceData
	HasCompany() bool
	// SetCompany sets the Company field with the given value.
	// It returns this SequenceData so that calls can be chained.
	SetCompany(value CompanySet) SequenceData
	// UnsetCompany removes the value of the Company field if it exists.
	// It returns this SequenceData so that calls can be chained.
	UnsetCompany() SequenceData

	// CreateCompany stores the related CompanyData to be used to create
	// a related record on the fly for Company.
	//
	// This method can be called multiple times to create multiple records
	CreateCompany(related CompanyData) SequenceData
	// CreateDate returns the value of the CreateDate field.
	// If this CreateDate is not set in this SequenceData, then
	// the Go zero value for the type is returned.
	CreateDate() dates.DateTime
	// HasCreateDate returns true if CreateDate is set in this SequenceData
	HasCreateDate() bool
	// SetCreateDate sets the CreateDate field with the given value.
	// It returns this SequenceData so that calls can be chained.
	SetCreateDate(value dates.DateTime) SequenceData
	// UnsetCreateDate removes the value of the CreateDate field if it exists.
	// It returns this SequenceData so that calls can be chained.
	UnsetCreateDate() SequenceData

	// CreateUID returns the value of the CreateUID field.
	// If this CreateUID is not set in this SequenceData, then
	// the Go zero value for the type is returned.
	CreateUID() int64
	// HasCreateUID returns true if CreateUID is set in this SequenceData
	HasCreateUID() bool
	// SetCreateUID sets the CreateUID field with the given value.
	// It returns this SequenceData so that calls can be chained.
	SetCreateUID(value int64) SequenceData
	// UnsetCreateUID removes the value of the CreateUID field if it exists.
	// It returns this SequenceData so that calls can be chained.
	UnsetCreateUID() SequenceData

	// DateRanges returns the value of the DateRanges field.
	// If this DateRanges is not set in this SequenceData, then
	// the Go zero value for the type is returned.
	DateRanges() SequenceDateRangeSet
	// HasDateRanges returns true if DateRanges is set in this SequenceData
	HasDateRanges() bool
	// SetDateRanges sets the DateRanges field with the given value.
	// It returns this SequenceData so that calls can be chained.
	SetDateRanges(value SequenceDateRangeSet) SequenceData
	// UnsetDateRanges removes the value of the DateRanges field if it exists.
	// It returns this SequenceData so that calls can be chained.
	UnsetDateRanges() SequenceData

	// CreateDateRanges stores the related SequenceDateRangeData to be used to create
	// a related record on the fly for DateRanges.
	//
	// This method can be called multiple times to create multiple records
	CreateDateRanges(related SequenceDateRangeData) SequenceData
	// DisplayName returns the value of the DisplayName field.
	// If this DisplayName is not set in this SequenceData, then
	// the Go zero value for the type is returned.
	DisplayName() string
	// HasDisplayName returns true if DisplayName is set in this SequenceData
	HasDisplayName() bool
	// SetDisplayName sets the DisplayName field with the given value.
	// It returns this SequenceData so that calls can be chained.
	SetDisplayName(value string) SequenceData
	// UnsetDisplayName removes the value of the DisplayName field if it exists.
	// It returns this SequenceData so that calls can be chained.
	UnsetDisplayName() SequenceData

	// HexyaExternalID returns the value of the HexyaExternalID field.
	// If this HexyaExternalID is not set in this SequenceData, then
	// the Go zero value for the type is returned.
	HexyaExternalID() string
	// HasHexyaExternalID returns true if HexyaExternalID is set in this SequenceData
	HasHexyaExternalID() bool
	// SetHexyaExternalID sets the HexyaExternalID field with the given value.
	// It returns this SequenceData so that calls can be chained.
	SetHexyaExternalID(value string) SequenceData
	// UnsetHexyaExternalID removes the value of the HexyaExternalID field if it exists.
	// It returns this SequenceData so that calls can be chained.
	UnsetHexyaExternalID() SequenceData

	// HexyaVersion returns the value of the HexyaVersion field.
	// If this HexyaVersion is not set in this SequenceData, then
	// the Go zero value for the type is returned.
	HexyaVersion() int
	// HasHexyaVersion returns true if HexyaVersion is set in this SequenceData
	HasHexyaVersion() bool
	// SetHexyaVersion sets the HexyaVersion field with the given value.
	// It returns this SequenceData so that calls can be chained.
	SetHexyaVersion(value int) SequenceData
	// UnsetHexyaVersion removes the value of the HexyaVersion field if it exists.
	// It returns this SequenceData so that calls can be chained.
	UnsetHexyaVersion() SequenceData

	// ID returns the value of the ID field.
	// If this ID is not set in this SequenceData, then
	// the Go zero value for the type is returned.
	ID() int64
	// HasID returns true if ID is set in this SequenceData
	HasID() bool
	// SetID sets the ID field with the given value.
	// It returns this SequenceData so that calls can be chained.
	SetID(value int64) SequenceData
	// UnsetID removes the value of the ID field if it exists.
	// It returns this SequenceData so that calls can be chained.
	UnsetID() SequenceData

	// Implementation returns the value of the Implementation field.
	// If this Implementation is not set in this SequenceData, then
	// the Go zero value for the type is returned.
	Implementation() string
	// HasImplementation returns true if Implementation is set in this SequenceData
	HasImplementation() bool
	// SetImplementation sets the Implementation field with the given value.
	// It returns this SequenceData so that calls can be chained.
	SetImplementation(value string) SequenceData
	// UnsetImplementation removes the value of the Implementation field if it exists.
	// It returns this SequenceData so that calls can be chained.
	UnsetImplementation() SequenceData

	// LastUpdate returns the value of the LastUpdate field.
	// If this LastUpdate is not set in this SequenceData, then
	// the Go zero value for the type is returned.
	LastUpdate() dates.DateTime
	// HasLastUpdate returns true if LastUpdate is set in this SequenceData
	HasLastUpdate() bool
	// SetLastUpdate sets the LastUpdate field with the given value.
	// It returns this SequenceData so that calls can be chained.
	SetLastUpdate(value dates.DateTime) SequenceData
	// UnsetLastUpdate removes the value of the LastUpdate field if it exists.
	// It returns this SequenceData so that calls can be chained.
	UnsetLastUpdate() SequenceData

	// Name returns the value of the Name field.
	// If this Name is not set in this SequenceData, then
	// the Go zero value for the type is returned.
	Name() string
	// HasName returns true if Name is set in this SequenceData
	HasName() bool
	// SetName sets the Name field with the given value.
	// It returns this SequenceData so that calls can be chained.
	SetName(value string) SequenceData
	// UnsetName removes the value of the Name field if it exists.
	// It returns this SequenceData so that calls can be chained.
	UnsetName() SequenceData

	// NumberIncrement returns the value of the NumberIncrement field.
	// If this NumberIncrement is not set in this SequenceData, then
	// the Go zero value for the type is returned.
	NumberIncrement() int64
	// HasNumberIncrement returns true if NumberIncrement is set in this SequenceData
	HasNumberIncrement() bool
	// SetNumberIncrement sets the NumberIncrement field with the given value.
	// It returns this SequenceData so that calls can be chained.
	SetNumberIncrement(value int64) SequenceData
	// UnsetNumberIncrement removes the value of the NumberIncrement field if it exists.
	// It returns this SequenceData so that calls can be chained.
	UnsetNumberIncrement() SequenceData

	// NumberNext returns the value of the NumberNext field.
	// If this NumberNext is not set in this SequenceData, then
	// the Go zero value for the type is returned.
	NumberNext() int64
	// HasNumberNext returns true if NumberNext is set in this SequenceData
	HasNumberNext() bool
	// SetNumberNext sets the NumberNext field with the given value.
	// It returns this SequenceData so that calls can be chained.
	SetNumberNext(value int64) SequenceData
	// UnsetNumberNext removes the value of the NumberNext field if it exists.
	// It returns this SequenceData so that calls can be chained.
	UnsetNumberNext() SequenceData

	// NumberNextActual returns the value of the NumberNextActual field.
	// If this NumberNextActual is not set in this SequenceData, then
	// the Go zero value for the type is returned.
	NumberNextActual() int64
	// HasNumberNextActual returns true if NumberNextActual is set in this SequenceData
	HasNumberNextActual() bool
	// SetNumberNextActual sets the NumberNextActual field with the given value.
	// It returns this SequenceData so that calls can be chained.
	SetNumberNextActual(value int64) SequenceData
	// UnsetNumberNextActual removes the value of the NumberNextActual field if it exists.
	// It returns this SequenceData so that calls can be chained.
	UnsetNumberNextActual() SequenceData

	// Padding returns the value of the Padding field.
	// If this Padding is not set in this SequenceData, then
	// the Go zero value for the type is returned.
	Padding() int64
	// HasPadding returns true if Padding is set in this SequenceData
	HasPadding() bool
	// SetPadding sets the Padding field with the given value.
	// It returns this SequenceData so that calls can be chained.
	SetPadding(value int64) SequenceData
	// UnsetPadding removes the value of the Padding field if it exists.
	// It returns this SequenceData so that calls can be chained.
	UnsetPadding() SequenceData

	// Prefix returns the value of the Prefix field.
	// If this Prefix is not set in this SequenceData, then
	// the Go zero value for the type is returned.
	Prefix() string
	// HasPrefix returns true if Prefix is set in this SequenceData
	HasPrefix() bool
	// SetPrefix sets the Prefix field with the given value.
	// It returns this SequenceData so that calls can be chained.
	SetPrefix(value string) SequenceData
	// UnsetPrefix removes the value of the Prefix field if it exists.
	// It returns this SequenceData so that calls can be chained.
	UnsetPrefix() SequenceData

	// Suffix returns the value of the Suffix field.
	// If this Suffix is not set in this SequenceData, then
	// the Go zero value for the type is returned.
	Suffix() string
	// HasSuffix returns true if Suffix is set in this SequenceData
	HasSuffix() bool
	// SetSuffix sets the Suffix field with the given value.
	// It returns this SequenceData so that calls can be chained.
	SetSuffix(value string) SequenceData
	// UnsetSuffix removes the value of the Suffix field if it exists.
	// It returns this SequenceData so that calls can be chained.
	UnsetSuffix() SequenceData

	// UseDateRange returns the value of the UseDateRange field.
	// If this UseDateRange is not set in this SequenceData, then
	// the Go zero value for the type is returned.
	UseDateRange() bool
	// HasUseDateRange returns true if UseDateRange is set in this SequenceData
	HasUseDateRange() bool
	// SetUseDateRange sets the UseDateRange field with the given value.
	// It returns this SequenceData so that calls can be chained.
	SetUseDateRange(value bool) SequenceData
	// UnsetUseDateRange removes the value of the UseDateRange field if it exists.
	// It returns this SequenceData so that calls can be chained.
	UnsetUseDateRange() SequenceData

	// WriteDate returns the value of the WriteDate field.
	// If this WriteDate is not set in this SequenceData, then
	// the Go zero value for the type is returned.
	WriteDate() dates.DateTime
	// HasWriteDate returns true if WriteDate is set in this SequenceData
	HasWriteDate() bool
	// SetWriteDate sets the WriteDate field with the given value.
	// It returns this SequenceData so that calls can be chained.
	SetWriteDate(value dates.DateTime) SequenceData
	// UnsetWriteDate removes the value of the WriteDate field if it exists.
	// It returns this SequenceData so that calls can be chained.
	UnsetWriteDate() SequenceData

	// WriteUID returns the value of the WriteUID field.
	// If this WriteUID is not set in this SequenceData, then
	// the Go zero value for the type is returned.
	WriteUID() int64
	// HasWriteUID returns true if WriteUID is set in this SequenceData
	HasWriteUID() bool
	// SetWriteUID sets the WriteUID field with the given value.
	// It returns this SequenceData so that calls can be chained.
	SetWriteUID(value int64) SequenceData
	// UnsetWriteUID removes the value of the WriteUID field if it exists.
	// It returns this SequenceData so that calls can be chained.
	UnsetWriteUID() SequenceData
}

// A SequenceGroupAggregateRow holds a row of results of a query with a group by clause
type SequenceGroupAggregateRow interface {
	// Values() returns the values of the actual query
	Values() SequenceData
	// Count is the number of lines aggregated into this one
	Count() int
	// Condition can be used to query the aggregated rows separately if needed
	Condition() q.SequenceCondition
}
