// This file is autogenerated by hexya-generate
// DO NOT MODIFY THIS FILE - ANY CHANGES WILL BE OVERWRITTEN

package q

import (
	"github.com/hexya-erp/hexya/src/models"
	"github.com/hexya-erp/pool/q/base_mixin"
)

type BaseMixinCondition = base_mixin.Condition

// BaseMixin returns a base_mixin.ConditionStart for BaseMixinModel
func BaseMixin() base_mixin.ConditionStart {
	return base_mixin.ConditionStart{
		ConditionStart: &models.ConditionStart{},
	}
}
