// This file is autogenerated by hexya-generate
// DO NOT MODIFY THIS FILE - ANY CHANGES WILL BE OVERWRITTEN

package q

import (
	"github.com/hexya-erp/hexya/src/models"
	"github.com/hexya-erp/pool/q/country"
)

type CountryCondition = country.Condition

// Country returns a country.ConditionStart for CountryModel
func Country() country.ConditionStart {
	return country.ConditionStart{
		ConditionStart: &models.ConditionStart{},
	}
}
