// This file is autogenerated by hexya-generate
// DO NOT MODIFY THIS FILE - ANY CHANGES WILL BE OVERWRITTEN

package q

import (
	"github.com/hexya-erp/hexya/src/models"
	"github.com/hexya-erp/pool/q/country_state"
)

type CountryStateCondition = country_state.Condition

// CountryState returns a country_state.ConditionStart for CountryStateModel
func CountryState() country_state.ConditionStart {
	return country_state.ConditionStart{
		ConditionStart: &models.ConditionStart{},
	}
}
