// This file is autogenerated by hexya-generate
// DO NOT MODIFY THIS FILE - ANY CHANGES WILL BE OVERWRITTEN

package q

import (
	"github.com/hexya-erp/hexya/src/models"
	"github.com/hexya-erp/pool/q/country_group"
)

type CountryGroupCondition = country_group.Condition

// CountryGroup returns a country_group.ConditionStart for CountryGroupModel
func CountryGroup() country_group.ConditionStart {
	return country_group.ConditionStart{
		ConditionStart: &models.ConditionStart{},
	}
}
