// This file is autogenerated by hexya-generate
// DO NOT MODIFY THIS FILE - ANY CHANGES WILL BE OVERWRITTEN

package q

import (
	"github.com/hexya-erp/hexya/src/models"
	"github.com/hexya-erp/pool/q/currency_rate"
)

type CurrencyRateCondition = currency_rate.Condition

// CurrencyRate returns a currency_rate.ConditionStart for CurrencyRateModel
func CurrencyRate() currency_rate.ConditionStart {
	return currency_rate.ConditionStart{
		ConditionStart: &models.ConditionStart{},
	}
}
