// This file is autogenerated by hexya-generate
// DO NOT MODIFY THIS FILE - ANY CHANGES WILL BE OVERWRITTEN

package q

import (
	"github.com/hexya-erp/hexya/src/models"
	"github.com/hexya-erp/pool/q/model_mixin"
)

type ModelMixinCondition = model_mixin.Condition

// ModelMixin returns a model_mixin.ConditionStart for ModelMixinModel
func ModelMixin() model_mixin.ConditionStart {
	return model_mixin.ConditionStart{
		ConditionStart: &models.ConditionStart{},
	}
}
