// This file is autogenerated by hexya-generate
// DO NOT MODIFY THIS FILE - ANY CHANGES WILL BE OVERWRITTEN

package q

import (
	"github.com/hexya-erp/hexya/src/models"
	"github.com/hexya-erp/pool/q/partner_title"
)

type PartnerTitleCondition = partner_title.Condition

// PartnerTitle returns a partner_title.ConditionStart for PartnerTitleModel
func PartnerTitle() partner_title.ConditionStart {
	return partner_title.ConditionStart{
		ConditionStart: &models.ConditionStart{},
	}
}
