// This file is autogenerated by hexya-generate
// DO NOT MODIFY THIS FILE - ANY CHANGES WILL BE OVERWRITTEN

package q

import (
	"github.com/hexya-erp/hexya/src/models"
	"github.com/hexya-erp/pool/q/queue_channel"
)

type QueueChannelCondition = queue_channel.Condition

// QueueChannel returns a queue_channel.ConditionStart for QueueChannelModel
func QueueChannel() queue_channel.ConditionStart {
	return queue_channel.ConditionStart{
		ConditionStart: &models.ConditionStart{},
	}
}
