// This file is autogenerated by hexya-generate
// DO NOT MODIFY THIS FILE - ANY CHANGES WILL BE OVERWRITTEN

package q

import (
	"github.com/hexya-erp/hexya/src/models"
	"github.com/hexya-erp/pool/q/sequence_date_range"
)

type SequenceDateRangeCondition = sequence_date_range.Condition

// SequenceDateRange returns a sequence_date_range.ConditionStart for SequenceDateRangeModel
func SequenceDateRange() sequence_date_range.ConditionStart {
	return sequence_date_range.ConditionStart{
		ConditionStart: &models.ConditionStart{},
	}
}
