// This file is autogenerated by hexya-generate
// DO NOT MODIFY THIS FILE - ANY CHANGES WILL BE OVERWRITTEN

package q

import (
	"github.com/hexya-erp/hexya/src/models"
	"github.com/hexya-erp/pool/q/sequence"
)

type SequenceCondition = sequence.Condition

// Sequence returns a sequence.ConditionStart for SequenceModel
func Sequence() sequence.ConditionStart {
	return sequence.ConditionStart{
		ConditionStart: &models.ConditionStart{},
	}
}
