// This file is autogenerated by hexya-generate
// DO NOT MODIFY THIS FILE - ANY CHANGES WILL BE OVERWRITTEN

package q

import (
	"github.com/hexya-erp/hexya/src/models"
	"github.com/hexya-erp/pool/q/translation"
)

type TranslationCondition = translation.Condition

// Translation returns a translation.ConditionStart for TranslationModel
func Translation() translation.ConditionStart {
	return translation.ConditionStart{
		ConditionStart: &models.ConditionStart{},
	}
}
