// This file is autogenerated by hexya-generate
// DO NOT MODIFY THIS FILE - ANY CHANGES WILL BE OVERWRITTEN

package q

import (
	"github.com/hexya-erp/hexya/src/models"
	"github.com/hexya-erp/pool/q/user_change_password_wizard"
)

type UserChangePasswordWizardCondition = user_change_password_wizard.Condition

// UserChangePasswordWizard returns a user_change_password_wizard.ConditionStart for UserChangePasswordWizardModel
func UserChangePasswordWizard() user_change_password_wizard.ConditionStart {
	return user_change_password_wizard.ConditionStart{
		ConditionStart: &models.ConditionStart{},
	}
}
