// This file is autogenerated by hexya-generate
// DO NOT MODIFY THIS FILE - ANY CHANGES WILL BE OVERWRITTEN

package q

import (
	"github.com/hexya-erp/hexya/src/models"
	"github.com/hexya-erp/pool/q/user"
)

type UserCondition = user.Condition

// User returns a user.ConditionStart for UserModel
func User() user.ConditionStart {
	return user.ConditionStart{
		ConditionStart: &models.ConditionStart{},
	}
}
