// This file is autogenerated by hexya-generate
// DO NOT MODIFY THIS FILE - ANY CHANGES WILL BE OVERWRITTEN

package h

import (
	"github.com/hexya-erp/hexya/src/models"
	"github.com/hexya-erp/pool/h/bank_account"
	"github.com/hexya-erp/pool/m"
	"github.com/hexya-erp/pool/q"
)

// ------- MODEL ---------

// BankAccountModel is a strongly typed model definition that is used
// to extend the BankAccount model or to get a BankAccountSet through
// its NewSet() function.
//
// To get the unique instance of this type, call BankAccount().
type BankAccountModel struct {
	*models.Model
}

// NewSet returns a new BankAccountSet instance in the given Environment
func (md BankAccountModel) NewSet(env models.Environment) m.BankAccountSet {
	return bank_account.BankAccountSet{
		RecordCollection: env.Pool("BankAccount"),
	}
}

// Create creates a new BankAccount record and returns the newly created
// BankAccountSet instance.
func (md BankAccountModel) Create(env models.Environment, data m.BankAccountData) m.BankAccountSet {
	return bank_account.BankAccountSet{
		RecordCollection: md.Model.Create(env, data),
	}
}

// Search searches the database and returns a new BankAccountSet instance
// with the records found.
func (md BankAccountModel) Search(env models.Environment, cond q.BankAccountCondition) m.BankAccountSet {
	return bank_account.BankAccountSet{
		RecordCollection: md.Model.Search(env, cond),
	}
}

// Browse returns a new RecordSet with the records with the given ids.
// Note that this function is just a shorcut for Search on a list of ids.
func (md BankAccountModel) Browse(env models.Environment, ids []int64) m.BankAccountSet {
	return bank_account.BankAccountSet{
		RecordCollection: md.Model.Browse(env, ids),
	}
}

// BrowseOne returns a new RecordSet with the record with the given id.
// Note that this function is just a shorcut for Search on the given id.
func (md BankAccountModel) BrowseOne(env models.Environment, id int64) m.BankAccountSet {
	return bank_account.BankAccountSet{
		RecordCollection: md.Model.BrowseOne(env, id),
	}
}

// NewData returns a pointer to a new empty BankAccountData instance.
//
// Optional field maps if given will be used to populate the data.
func (md BankAccountModel) NewData(fm ...models.FieldMap) m.BankAccountData {
	return &bank_account.BankAccountData{
		ModelData: models.NewModelData(BankAccount(), fm...),
	}
}

// Fields returns the Field Collection of the BankAccount Model
func (md BankAccountModel) Fields() bank_account.FieldsCollection {
	return bank_account.FieldsCollection{
		FieldsCollection: md.Model.Fields(),
	}
}

// Methods returns the Method Collection of the BankAccount Model
func (md BankAccountModel) Methods() bank_account.MethodsCollection {
	return bank_account.MethodsCollection{
		MethodsCollection: md.Model.Methods(),
	}
}

// Underlying returns the underlying models.Model instance
func (md BankAccountModel) Underlying() *models.Model {
	return md.Model
}

var _ models.Modeler = BankAccountModel{}

// Coalesce takes a list of BankAccountSet and return the first non-empty one
// if every record set is empty, it will return the last given
func (md BankAccountModel) Coalesce(lst ...m.BankAccountSet) m.BankAccountSet {
	var last m.BankAccountSet
	for _, elem := range lst {
		if elem.Collection().IsNotEmpty() {
			return elem
		}
		last = elem
	}
	return last
}

// BankAccount returns the unique instance of the BankAccountModel type
// which is used to extend the BankAccount model or to get a BankAccountSet through
// its NewSet() function.
func BankAccount() BankAccountModel {
	return BankAccountModel{
		Model: models.Registry.MustGet("BankAccount"),
	}
}
