// This file is autogenerated by hexya-generate
// DO NOT MODIFY THIS FILE - ANY CHANGES WILL BE OVERWRITTEN

package h

import (
	"github.com/hexya-erp/hexya/src/models"
	"github.com/hexya-erp/pool/h/country"
	"github.com/hexya-erp/pool/m"
	"github.com/hexya-erp/pool/q"
)

// ------- MODEL ---------

// CountryModel is a strongly typed model definition that is used
// to extend the Country model or to get a CountrySet through
// its NewSet() function.
//
// To get the unique instance of this type, call Country().
type CountryModel struct {
	*models.Model
}

// NewSet returns a new CountrySet instance in the given Environment
func (md CountryModel) NewSet(env models.Environment) m.CountrySet {
	return country.CountrySet{
		RecordCollection: env.Pool("Country"),
	}
}

// Create creates a new Country record and returns the newly created
// CountrySet instance.
func (md CountryModel) Create(env models.Environment, data m.CountryData) m.CountrySet {
	return country.CountrySet{
		RecordCollection: md.Model.Create(env, data),
	}
}

// Search searches the database and returns a new CountrySet instance
// with the records found.
func (md CountryModel) Search(env models.Environment, cond q.CountryCondition) m.CountrySet {
	return country.CountrySet{
		RecordCollection: md.Model.Search(env, cond),
	}
}

// Browse returns a new RecordSet with the records with the given ids.
// Note that this function is just a shorcut for Search on a list of ids.
func (md CountryModel) Browse(env models.Environment, ids []int64) m.CountrySet {
	return country.CountrySet{
		RecordCollection: md.Model.Browse(env, ids),
	}
}

// BrowseOne returns a new RecordSet with the record with the given id.
// Note that this function is just a shorcut for Search on the given id.
func (md CountryModel) BrowseOne(env models.Environment, id int64) m.CountrySet {
	return country.CountrySet{
		RecordCollection: md.Model.BrowseOne(env, id),
	}
}

// NewData returns a pointer to a new empty CountryData instance.
//
// Optional field maps if given will be used to populate the data.
func (md CountryModel) NewData(fm ...models.FieldMap) m.CountryData {
	return &country.CountryData{
		ModelData: models.NewModelData(Country(), fm...),
	}
}

// Fields returns the Field Collection of the Country Model
func (md CountryModel) Fields() country.FieldsCollection {
	return country.FieldsCollection{
		FieldsCollection: md.Model.Fields(),
	}
}

// Methods returns the Method Collection of the Country Model
func (md CountryModel) Methods() country.MethodsCollection {
	return country.MethodsCollection{
		MethodsCollection: md.Model.Methods(),
	}
}

// Underlying returns the underlying models.Model instance
func (md CountryModel) Underlying() *models.Model {
	return md.Model
}

var _ models.Modeler = CountryModel{}

// Coalesce takes a list of CountrySet and return the first non-empty one
// if every record set is empty, it will return the last given
func (md CountryModel) Coalesce(lst ...m.CountrySet) m.CountrySet {
	var last m.CountrySet
	for _, elem := range lst {
		if elem.Collection().IsNotEmpty() {
			return elem
		}
		last = elem
	}
	return last
}

// Country returns the unique instance of the CountryModel type
// which is used to extend the Country model or to get a CountrySet through
// its NewSet() function.
func Country() CountryModel {
	return CountryModel{
		Model: models.Registry.MustGet("Country"),
	}
}
