// This file is autogenerated by hexya-generate
// DO NOT MODIFY THIS FILE - ANY CHANGES WILL BE OVERWRITTEN

package h

import (
	"github.com/hexya-erp/hexya/src/models"
	"github.com/hexya-erp/pool/h/country_group"
	"github.com/hexya-erp/pool/m"
	"github.com/hexya-erp/pool/q"
)

// ------- MODEL ---------

// CountryGroupModel is a strongly typed model definition that is used
// to extend the CountryGroup model or to get a CountryGroupSet through
// its NewSet() function.
//
// To get the unique instance of this type, call CountryGroup().
type CountryGroupModel struct {
	*models.Model
}

// NewSet returns a new CountryGroupSet instance in the given Environment
func (md CountryGroupModel) NewSet(env models.Environment) m.CountryGroupSet {
	return country_group.CountryGroupSet{
		RecordCollection: env.Pool("CountryGroup"),
	}
}

// Create creates a new CountryGroup record and returns the newly created
// CountryGroupSet instance.
func (md CountryGroupModel) Create(env models.Environment, data m.CountryGroupData) m.CountryGroupSet {
	return country_group.CountryGroupSet{
		RecordCollection: md.Model.Create(env, data),
	}
}

// Search searches the database and returns a new CountryGroupSet instance
// with the records found.
func (md CountryGroupModel) Search(env models.Environment, cond q.CountryGroupCondition) m.CountryGroupSet {
	return country_group.CountryGroupSet{
		RecordCollection: md.Model.Search(env, cond),
	}
}

// Browse returns a new RecordSet with the records with the given ids.
// Note that this function is just a shorcut for Search on a list of ids.
func (md CountryGroupModel) Browse(env models.Environment, ids []int64) m.CountryGroupSet {
	return country_group.CountryGroupSet{
		RecordCollection: md.Model.Browse(env, ids),
	}
}

// BrowseOne returns a new RecordSet with the record with the given id.
// Note that this function is just a shorcut for Search on the given id.
func (md CountryGroupModel) BrowseOne(env models.Environment, id int64) m.CountryGroupSet {
	return country_group.CountryGroupSet{
		RecordCollection: md.Model.BrowseOne(env, id),
	}
}

// NewData returns a pointer to a new empty CountryGroupData instance.
//
// Optional field maps if given will be used to populate the data.
func (md CountryGroupModel) NewData(fm ...models.FieldMap) m.CountryGroupData {
	return &country_group.CountryGroupData{
		ModelData: models.NewModelData(CountryGroup(), fm...),
	}
}

// Fields returns the Field Collection of the CountryGroup Model
func (md CountryGroupModel) Fields() country_group.FieldsCollection {
	return country_group.FieldsCollection{
		FieldsCollection: md.Model.Fields(),
	}
}

// Methods returns the Method Collection of the CountryGroup Model
func (md CountryGroupModel) Methods() country_group.MethodsCollection {
	return country_group.MethodsCollection{
		MethodsCollection: md.Model.Methods(),
	}
}

// Underlying returns the underlying models.Model instance
func (md CountryGroupModel) Underlying() *models.Model {
	return md.Model
}

var _ models.Modeler = CountryGroupModel{}

// Coalesce takes a list of CountryGroupSet and return the first non-empty one
// if every record set is empty, it will return the last given
func (md CountryGroupModel) Coalesce(lst ...m.CountryGroupSet) m.CountryGroupSet {
	var last m.CountryGroupSet
	for _, elem := range lst {
		if elem.Collection().IsNotEmpty() {
			return elem
		}
		last = elem
	}
	return last
}

// CountryGroup returns the unique instance of the CountryGroupModel type
// which is used to extend the CountryGroup model or to get a CountryGroupSet through
// its NewSet() function.
func CountryGroup() CountryGroupModel {
	return CountryGroupModel{
		Model: models.Registry.MustGet("CountryGroup"),
	}
}
