// This file is autogenerated by hexya-generate
// DO NOT MODIFY THIS FILE - ANY CHANGES WILL BE OVERWRITTEN

package h

import (
	"github.com/hexya-erp/hexya/src/models"
	"github.com/hexya-erp/pool/h/cron"
	"github.com/hexya-erp/pool/m"
	"github.com/hexya-erp/pool/q"
)

// ------- MODEL ---------

// CronModel is a strongly typed model definition that is used
// to extend the Cron model or to get a CronSet through
// its NewSet() function.
//
// To get the unique instance of this type, call Cron().
type CronModel struct {
	*models.Model
}

// NewSet returns a new CronSet instance in the given Environment
func (md CronModel) NewSet(env models.Environment) m.CronSet {
	return cron.CronSet{
		RecordCollection: env.Pool("Cron"),
	}
}

// Create creates a new Cron record and returns the newly created
// CronSet instance.
func (md CronModel) Create(env models.Environment, data m.CronData) m.CronSet {
	return cron.CronSet{
		RecordCollection: md.Model.Create(env, data),
	}
}

// Search searches the database and returns a new CronSet instance
// with the records found.
func (md CronModel) Search(env models.Environment, cond q.CronCondition) m.CronSet {
	return cron.CronSet{
		RecordCollection: md.Model.Search(env, cond),
	}
}

// Browse returns a new RecordSet with the records with the given ids.
// Note that this function is just a shorcut for Search on a list of ids.
func (md CronModel) Browse(env models.Environment, ids []int64) m.CronSet {
	return cron.CronSet{
		RecordCollection: md.Model.Browse(env, ids),
	}
}

// BrowseOne returns a new RecordSet with the record with the given id.
// Note that this function is just a shorcut for Search on the given id.
func (md CronModel) BrowseOne(env models.Environment, id int64) m.CronSet {
	return cron.CronSet{
		RecordCollection: md.Model.BrowseOne(env, id),
	}
}

// NewData returns a pointer to a new empty CronData instance.
//
// Optional field maps if given will be used to populate the data.
func (md CronModel) NewData(fm ...models.FieldMap) m.CronData {
	return &cron.CronData{
		ModelData: models.NewModelData(Cron(), fm...),
	}
}

// Fields returns the Field Collection of the Cron Model
func (md CronModel) Fields() cron.FieldsCollection {
	return cron.FieldsCollection{
		FieldsCollection: md.Model.Fields(),
	}
}

// Methods returns the Method Collection of the Cron Model
func (md CronModel) Methods() cron.MethodsCollection {
	return cron.MethodsCollection{
		MethodsCollection: md.Model.Methods(),
	}
}

// Underlying returns the underlying models.Model instance
func (md CronModel) Underlying() *models.Model {
	return md.Model
}

var _ models.Modeler = CronModel{}

// Coalesce takes a list of CronSet and return the first non-empty one
// if every record set is empty, it will return the last given
func (md CronModel) Coalesce(lst ...m.CronSet) m.CronSet {
	var last m.CronSet
	for _, elem := range lst {
		if elem.Collection().IsNotEmpty() {
			return elem
		}
		last = elem
	}
	return last
}

// Cron returns the unique instance of the CronModel type
// which is used to extend the Cron model or to get a CronSet through
// its NewSet() function.
func Cron() CronModel {
	return CronModel{
		Model: models.Registry.MustGet("Cron"),
	}
}
