// This file is autogenerated by hexya-generate
// DO NOT MODIFY THIS FILE - ANY CHANGES WILL BE OVERWRITTEN

package h

import (
	"github.com/hexya-erp/hexya/src/models"
	"github.com/hexya-erp/pool/h/currency_rate"
	"github.com/hexya-erp/pool/m"
	"github.com/hexya-erp/pool/q"
)

// ------- MODEL ---------

// CurrencyRateModel is a strongly typed model definition that is used
// to extend the CurrencyRate model or to get a CurrencyRateSet through
// its NewSet() function.
//
// To get the unique instance of this type, call CurrencyRate().
type CurrencyRateModel struct {
	*models.Model
}

// NewSet returns a new CurrencyRateSet instance in the given Environment
func (md CurrencyRateModel) NewSet(env models.Environment) m.CurrencyRateSet {
	return currency_rate.CurrencyRateSet{
		RecordCollection: env.Pool("CurrencyRate"),
	}
}

// Create creates a new CurrencyRate record and returns the newly created
// CurrencyRateSet instance.
func (md CurrencyRateModel) Create(env models.Environment, data m.CurrencyRateData) m.CurrencyRateSet {
	return currency_rate.CurrencyRateSet{
		RecordCollection: md.Model.Create(env, data),
	}
}

// Search searches the database and returns a new CurrencyRateSet instance
// with the records found.
func (md CurrencyRateModel) Search(env models.Environment, cond q.CurrencyRateCondition) m.CurrencyRateSet {
	return currency_rate.CurrencyRateSet{
		RecordCollection: md.Model.Search(env, cond),
	}
}

// Browse returns a new RecordSet with the records with the given ids.
// Note that this function is just a shorcut for Search on a list of ids.
func (md CurrencyRateModel) Browse(env models.Environment, ids []int64) m.CurrencyRateSet {
	return currency_rate.CurrencyRateSet{
		RecordCollection: md.Model.Browse(env, ids),
	}
}

// BrowseOne returns a new RecordSet with the record with the given id.
// Note that this function is just a shorcut for Search on the given id.
func (md CurrencyRateModel) BrowseOne(env models.Environment, id int64) m.CurrencyRateSet {
	return currency_rate.CurrencyRateSet{
		RecordCollection: md.Model.BrowseOne(env, id),
	}
}

// NewData returns a pointer to a new empty CurrencyRateData instance.
//
// Optional field maps if given will be used to populate the data.
func (md CurrencyRateModel) NewData(fm ...models.FieldMap) m.CurrencyRateData {
	return &currency_rate.CurrencyRateData{
		ModelData: models.NewModelData(CurrencyRate(), fm...),
	}
}

// Fields returns the Field Collection of the CurrencyRate Model
func (md CurrencyRateModel) Fields() currency_rate.FieldsCollection {
	return currency_rate.FieldsCollection{
		FieldsCollection: md.Model.Fields(),
	}
}

// Methods returns the Method Collection of the CurrencyRate Model
func (md CurrencyRateModel) Methods() currency_rate.MethodsCollection {
	return currency_rate.MethodsCollection{
		MethodsCollection: md.Model.Methods(),
	}
}

// Underlying returns the underlying models.Model instance
func (md CurrencyRateModel) Underlying() *models.Model {
	return md.Model
}

var _ models.Modeler = CurrencyRateModel{}

// Coalesce takes a list of CurrencyRateSet and return the first non-empty one
// if every record set is empty, it will return the last given
func (md CurrencyRateModel) Coalesce(lst ...m.CurrencyRateSet) m.CurrencyRateSet {
	var last m.CurrencyRateSet
	for _, elem := range lst {
		if elem.Collection().IsNotEmpty() {
			return elem
		}
		last = elem
	}
	return last
}

// CurrencyRate returns the unique instance of the CurrencyRateModel type
// which is used to extend the CurrencyRate model or to get a CurrencyRateSet through
// its NewSet() function.
func CurrencyRate() CurrencyRateModel {
	return CurrencyRateModel{
		Model: models.Registry.MustGet("CurrencyRate"),
	}
}
