// This file is autogenerated by hexya-generate
// DO NOT MODIFY THIS FILE - ANY CHANGES WILL BE OVERWRITTEN

package h

import (
	"github.com/hexya-erp/hexya/src/models"
	"github.com/hexya-erp/pool/h/partner_industry"
	"github.com/hexya-erp/pool/m"
	"github.com/hexya-erp/pool/q"
)

// ------- MODEL ---------

// PartnerIndustryModel is a strongly typed model definition that is used
// to extend the PartnerIndustry model or to get a PartnerIndustrySet through
// its NewSet() function.
//
// To get the unique instance of this type, call PartnerIndustry().
type PartnerIndustryModel struct {
	*models.Model
}

// NewSet returns a new PartnerIndustrySet instance in the given Environment
func (md PartnerIndustryModel) NewSet(env models.Environment) m.PartnerIndustrySet {
	return partner_industry.PartnerIndustrySet{
		RecordCollection: env.Pool("PartnerIndustry"),
	}
}

// Create creates a new PartnerIndustry record and returns the newly created
// PartnerIndustrySet instance.
func (md PartnerIndustryModel) Create(env models.Environment, data m.PartnerIndustryData) m.PartnerIndustrySet {
	return partner_industry.PartnerIndustrySet{
		RecordCollection: md.Model.Create(env, data),
	}
}

// Search searches the database and returns a new PartnerIndustrySet instance
// with the records found.
func (md PartnerIndustryModel) Search(env models.Environment, cond q.PartnerIndustryCondition) m.PartnerIndustrySet {
	return partner_industry.PartnerIndustrySet{
		RecordCollection: md.Model.Search(env, cond),
	}
}

// Browse returns a new RecordSet with the records with the given ids.
// Note that this function is just a shorcut for Search on a list of ids.
func (md PartnerIndustryModel) Browse(env models.Environment, ids []int64) m.PartnerIndustrySet {
	return partner_industry.PartnerIndustrySet{
		RecordCollection: md.Model.Browse(env, ids),
	}
}

// BrowseOne returns a new RecordSet with the record with the given id.
// Note that this function is just a shorcut for Search on the given id.
func (md PartnerIndustryModel) BrowseOne(env models.Environment, id int64) m.PartnerIndustrySet {
	return partner_industry.PartnerIndustrySet{
		RecordCollection: md.Model.BrowseOne(env, id),
	}
}

// NewData returns a pointer to a new empty PartnerIndustryData instance.
//
// Optional field maps if given will be used to populate the data.
func (md PartnerIndustryModel) NewData(fm ...models.FieldMap) m.PartnerIndustryData {
	return &partner_industry.PartnerIndustryData{
		ModelData: models.NewModelData(PartnerIndustry(), fm...),
	}
}

// Fields returns the Field Collection of the PartnerIndustry Model
func (md PartnerIndustryModel) Fields() partner_industry.FieldsCollection {
	return partner_industry.FieldsCollection{
		FieldsCollection: md.Model.Fields(),
	}
}

// Methods returns the Method Collection of the PartnerIndustry Model
func (md PartnerIndustryModel) Methods() partner_industry.MethodsCollection {
	return partner_industry.MethodsCollection{
		MethodsCollection: md.Model.Methods(),
	}
}

// Underlying returns the underlying models.Model instance
func (md PartnerIndustryModel) Underlying() *models.Model {
	return md.Model
}

var _ models.Modeler = PartnerIndustryModel{}

// Coalesce takes a list of PartnerIndustrySet and return the first non-empty one
// if every record set is empty, it will return the last given
func (md PartnerIndustryModel) Coalesce(lst ...m.PartnerIndustrySet) m.PartnerIndustrySet {
	var last m.PartnerIndustrySet
	for _, elem := range lst {
		if elem.Collection().IsNotEmpty() {
			return elem
		}
		last = elem
	}
	return last
}

// PartnerIndustry returns the unique instance of the PartnerIndustryModel type
// which is used to extend the PartnerIndustry model or to get a PartnerIndustrySet through
// its NewSet() function.
func PartnerIndustry() PartnerIndustryModel {
	return PartnerIndustryModel{
		Model: models.Registry.MustGet("PartnerIndustry"),
	}
}
