// This file is autogenerated by hexya-generate
// DO NOT MODIFY THIS FILE - ANY CHANGES WILL BE OVERWRITTEN

package h

import (
	"github.com/hexya-erp/hexya/src/models"
	"github.com/hexya-erp/pool/h/queue_channel"
	"github.com/hexya-erp/pool/m"
	"github.com/hexya-erp/pool/q"
)

// ------- MODEL ---------

// QueueChannelModel is a strongly typed model definition that is used
// to extend the QueueChannel model or to get a QueueChannelSet through
// its NewSet() function.
//
// To get the unique instance of this type, call QueueChannel().
type QueueChannelModel struct {
	*models.Model
}

// NewSet returns a new QueueChannelSet instance in the given Environment
func (md QueueChannelModel) NewSet(env models.Environment) m.QueueChannelSet {
	return queue_channel.QueueChannelSet{
		RecordCollection: env.Pool("QueueChannel"),
	}
}

// Create creates a new QueueChannel record and returns the newly created
// QueueChannelSet instance.
func (md QueueChannelModel) Create(env models.Environment, data m.QueueChannelData) m.QueueChannelSet {
	return queue_channel.QueueChannelSet{
		RecordCollection: md.Model.Create(env, data),
	}
}

// Search searches the database and returns a new QueueChannelSet instance
// with the records found.
func (md QueueChannelModel) Search(env models.Environment, cond q.QueueChannelCondition) m.QueueChannelSet {
	return queue_channel.QueueChannelSet{
		RecordCollection: md.Model.Search(env, cond),
	}
}

// Browse returns a new RecordSet with the records with the given ids.
// Note that this function is just a shorcut for Search on a list of ids.
func (md QueueChannelModel) Browse(env models.Environment, ids []int64) m.QueueChannelSet {
	return queue_channel.QueueChannelSet{
		RecordCollection: md.Model.Browse(env, ids),
	}
}

// BrowseOne returns a new RecordSet with the record with the given id.
// Note that this function is just a shorcut for Search on the given id.
func (md QueueChannelModel) BrowseOne(env models.Environment, id int64) m.QueueChannelSet {
	return queue_channel.QueueChannelSet{
		RecordCollection: md.Model.BrowseOne(env, id),
	}
}

// NewData returns a pointer to a new empty QueueChannelData instance.
//
// Optional field maps if given will be used to populate the data.
func (md QueueChannelModel) NewData(fm ...models.FieldMap) m.QueueChannelData {
	return &queue_channel.QueueChannelData{
		ModelData: models.NewModelData(QueueChannel(), fm...),
	}
}

// Fields returns the Field Collection of the QueueChannel Model
func (md QueueChannelModel) Fields() queue_channel.FieldsCollection {
	return queue_channel.FieldsCollection{
		FieldsCollection: md.Model.Fields(),
	}
}

// Methods returns the Method Collection of the QueueChannel Model
func (md QueueChannelModel) Methods() queue_channel.MethodsCollection {
	return queue_channel.MethodsCollection{
		MethodsCollection: md.Model.Methods(),
	}
}

// Underlying returns the underlying models.Model instance
func (md QueueChannelModel) Underlying() *models.Model {
	return md.Model
}

var _ models.Modeler = QueueChannelModel{}

// Coalesce takes a list of QueueChannelSet and return the first non-empty one
// if every record set is empty, it will return the last given
func (md QueueChannelModel) Coalesce(lst ...m.QueueChannelSet) m.QueueChannelSet {
	var last m.QueueChannelSet
	for _, elem := range lst {
		if elem.Collection().IsNotEmpty() {
			return elem
		}
		last = elem
	}
	return last
}

// QueueChannel returns the unique instance of the QueueChannelModel type
// which is used to extend the QueueChannel model or to get a QueueChannelSet through
// its NewSet() function.
func QueueChannel() QueueChannelModel {
	return QueueChannelModel{
		Model: models.Registry.MustGet("QueueChannel"),
	}
}
