// This file is autogenerated by hexya-generate
// DO NOT MODIFY THIS FILE - ANY CHANGES WILL BE OVERWRITTEN

package h

import (
	"github.com/hexya-erp/hexya/src/models"
	"github.com/hexya-erp/pool/h/sequence_date_range"
	"github.com/hexya-erp/pool/m"
	"github.com/hexya-erp/pool/q"
)

// ------- MODEL ---------

// SequenceDateRangeModel is a strongly typed model definition that is used
// to extend the SequenceDateRange model or to get a SequenceDateRangeSet through
// its NewSet() function.
//
// To get the unique instance of this type, call SequenceDateRange().
type SequenceDateRangeModel struct {
	*models.Model
}

// NewSet returns a new SequenceDateRangeSet instance in the given Environment
func (md SequenceDateRangeModel) NewSet(env models.Environment) m.SequenceDateRangeSet {
	return sequence_date_range.SequenceDateRangeSet{
		RecordCollection: env.Pool("SequenceDateRange"),
	}
}

// Create creates a new SequenceDateRange record and returns the newly created
// SequenceDateRangeSet instance.
func (md SequenceDateRangeModel) Create(env models.Environment, data m.SequenceDateRangeData) m.SequenceDateRangeSet {
	return sequence_date_range.SequenceDateRangeSet{
		RecordCollection: md.Model.Create(env, data),
	}
}

// Search searches the database and returns a new SequenceDateRangeSet instance
// with the records found.
func (md SequenceDateRangeModel) Search(env models.Environment, cond q.SequenceDateRangeCondition) m.SequenceDateRangeSet {
	return sequence_date_range.SequenceDateRangeSet{
		RecordCollection: md.Model.Search(env, cond),
	}
}

// Browse returns a new RecordSet with the records with the given ids.
// Note that this function is just a shorcut for Search on a list of ids.
func (md SequenceDateRangeModel) Browse(env models.Environment, ids []int64) m.SequenceDateRangeSet {
	return sequence_date_range.SequenceDateRangeSet{
		RecordCollection: md.Model.Browse(env, ids),
	}
}

// BrowseOne returns a new RecordSet with the record with the given id.
// Note that this function is just a shorcut for Search on the given id.
func (md SequenceDateRangeModel) BrowseOne(env models.Environment, id int64) m.SequenceDateRangeSet {
	return sequence_date_range.SequenceDateRangeSet{
		RecordCollection: md.Model.BrowseOne(env, id),
	}
}

// NewData returns a pointer to a new empty SequenceDateRangeData instance.
//
// Optional field maps if given will be used to populate the data.
func (md SequenceDateRangeModel) NewData(fm ...models.FieldMap) m.SequenceDateRangeData {
	return &sequence_date_range.SequenceDateRangeData{
		ModelData: models.NewModelData(SequenceDateRange(), fm...),
	}
}

// Fields returns the Field Collection of the SequenceDateRange Model
func (md SequenceDateRangeModel) Fields() sequence_date_range.FieldsCollection {
	return sequence_date_range.FieldsCollection{
		FieldsCollection: md.Model.Fields(),
	}
}

// Methods returns the Method Collection of the SequenceDateRange Model
func (md SequenceDateRangeModel) Methods() sequence_date_range.MethodsCollection {
	return sequence_date_range.MethodsCollection{
		MethodsCollection: md.Model.Methods(),
	}
}

// Underlying returns the underlying models.Model instance
func (md SequenceDateRangeModel) Underlying() *models.Model {
	return md.Model
}

var _ models.Modeler = SequenceDateRangeModel{}

// Coalesce takes a list of SequenceDateRangeSet and return the first non-empty one
// if every record set is empty, it will return the last given
func (md SequenceDateRangeModel) Coalesce(lst ...m.SequenceDateRangeSet) m.SequenceDateRangeSet {
	var last m.SequenceDateRangeSet
	for _, elem := range lst {
		if elem.Collection().IsNotEmpty() {
			return elem
		}
		last = elem
	}
	return last
}

// SequenceDateRange returns the unique instance of the SequenceDateRangeModel type
// which is used to extend the SequenceDateRange model or to get a SequenceDateRangeSet through
// its NewSet() function.
func SequenceDateRange() SequenceDateRangeModel {
	return SequenceDateRangeModel{
		Model: models.Registry.MustGet("SequenceDateRange"),
	}
}
