// This file is autogenerated by hexya-generate
// DO NOT MODIFY THIS FILE - ANY CHANGES WILL BE OVERWRITTEN

package h

import (
	"github.com/hexya-erp/hexya/src/models"
	"github.com/hexya-erp/pool/h/user_log"
	"github.com/hexya-erp/pool/m"
	"github.com/hexya-erp/pool/q"
)

// ------- MODEL ---------

// UserLogModel is a strongly typed model definition that is used
// to extend the UserLog model or to get a UserLogSet through
// its NewSet() function.
//
// To get the unique instance of this type, call UserLog().
type UserLogModel struct {
	*models.Model
}

// NewSet returns a new UserLogSet instance in the given Environment
func (md UserLogModel) NewSet(env models.Environment) m.UserLogSet {
	return user_log.UserLogSet{
		RecordCollection: env.Pool("UserLog"),
	}
}

// Create creates a new UserLog record and returns the newly created
// UserLogSet instance.
func (md UserLogModel) Create(env models.Environment, data m.UserLogData) m.UserLogSet {
	return user_log.UserLogSet{
		RecordCollection: md.Model.Create(env, data),
	}
}

// Search searches the database and returns a new UserLogSet instance
// with the records found.
func (md UserLogModel) Search(env models.Environment, cond q.UserLogCondition) m.UserLogSet {
	return user_log.UserLogSet{
		RecordCollection: md.Model.Search(env, cond),
	}
}

// Browse returns a new RecordSet with the records with the given ids.
// Note that this function is just a shorcut for Search on a list of ids.
func (md UserLogModel) Browse(env models.Environment, ids []int64) m.UserLogSet {
	return user_log.UserLogSet{
		RecordCollection: md.Model.Browse(env, ids),
	}
}

// BrowseOne returns a new RecordSet with the record with the given id.
// Note that this function is just a shorcut for Search on the given id.
func (md UserLogModel) BrowseOne(env models.Environment, id int64) m.UserLogSet {
	return user_log.UserLogSet{
		RecordCollection: md.Model.BrowseOne(env, id),
	}
}

// NewData returns a pointer to a new empty UserLogData instance.
//
// Optional field maps if given will be used to populate the data.
func (md UserLogModel) NewData(fm ...models.FieldMap) m.UserLogData {
	return &user_log.UserLogData{
		ModelData: models.NewModelData(UserLog(), fm...),
	}
}

// Fields returns the Field Collection of the UserLog Model
func (md UserLogModel) Fields() user_log.FieldsCollection {
	return user_log.FieldsCollection{
		FieldsCollection: md.Model.Fields(),
	}
}

// Methods returns the Method Collection of the UserLog Model
func (md UserLogModel) Methods() user_log.MethodsCollection {
	return user_log.MethodsCollection{
		MethodsCollection: md.Model.Methods(),
	}
}

// Underlying returns the underlying models.Model instance
func (md UserLogModel) Underlying() *models.Model {
	return md.Model
}

var _ models.Modeler = UserLogModel{}

// Coalesce takes a list of UserLogSet and return the first non-empty one
// if every record set is empty, it will return the last given
func (md UserLogModel) Coalesce(lst ...m.UserLogSet) m.UserLogSet {
	var last m.UserLogSet
	for _, elem := range lst {
		if elem.Collection().IsNotEmpty() {
			return elem
		}
		last = elem
	}
	return last
}

// UserLog returns the unique instance of the UserLogModel type
// which is used to extend the UserLog model or to get a UserLogSet through
// its NewSet() function.
func UserLog() UserLogModel {
	return UserLogModel{
		Model: models.Registry.MustGet("UserLog"),
	}
}
